#!/usr/bin/env node
/**
 * docgen — per-directory AUTO_DOCS.md generator for Claude agents.
 *
 * Walks the repo, picks one (or all, with --until-done) directories
 * whose contents have changed since the last analysis (or were never
 * analyzed), feeds the directory's file content to `claude -p`, and
 * writes the response to `<dir>/AUTO_DOCS.md` with an auto-generated
 * marker. docgen OWNS this filename — a hand-authored `README.md` in
 * the same directory is invisible to docgen (humans own README.md),
 * so the two never collide.
 *
 * State (which dirs have been analyzed, with what file mtimes) lives
 * at `.docgen/state.json` at repo root. Staleness = any file added,
 * removed, or modified since last analysis.
 *
 * The whole point is to make Claude faster at navigating the codebase:
 * a stale grep / find isn't as good as a one-paragraph "this directory
 * does X, files are Y/Z/W, depends on A" written by a previous agent
 * with full context.
 *
 * USAGE
 *   docgen                       analyze one stale/uncovered dir, exit
 *   docgen --until-done          loop until every dir has fresh docs
 *   docgen --until-done --parallel 4   same, but up to 4 dirs in flight
 *                                  at the same tree depth — leaves at
 *                                  depth N parallelise, trunks at N-1
 *                                  wait for their children.
 *   docgen status                print coverage report (no analysis)
 *   docgen migrate               rename docgen-marked README.md → AUTO_DOCS.md
 *                                (pure file move, no claude calls; idempotent)
 *   docgen --dir <path>          force-analyze a specific directory
 *   docgen --dry-run             print what would be analyzed, do not call claude
 *   docgen --help                show this help
 *
 *   --parallel <n>               max concurrent claude calls within a
 *                                depth batch (default 1 — serial). Only
 *                                dirs at the same depth ever run
 *                                concurrently; bottom-up ordering is
 *                                preserved across depths.
 *   --scope <paths>              comma-separated list of paths (files or
 *                                dirs) to restrict the walk to. Each
 *                                path is expanded to include itself and
 *                                every ancestor up to repo root, so
 *                                trunk bubble-up still works. Used by
 *                                the pre-push hook to refresh only the
 *                                dirs containing files in the diff,
 *                                much cheaper than a full re-walk.
 *   --changed <dirs>             comma-separated relative dir paths to
 *                                restrict analysis to (plus ancestors).
 *                                Same semantics as --scope but takes
 *                                relative directory names rather than
 *                                file paths — used by the pre-push hook
 *                                to pass the push diff's changed dirs.
 *                                Absent = full sweep (default).
 *   --model <name>               override claude model (default: DOCGEN_MODEL, see models.mjs)
 *   --timeout-ms <n>             per-call timeout (default 300000 = 5 min)
 *
 * The CLI is designed for one-shot invocation by humans, cron, or a
 * future PR-merge hook. State is durable; rerunning picks up where the
 * last run stopped.
 *
 * No shell execution: all subprocess calls use `spawn` / `execFileSync`
 * with explicit argv arrays — no string interpolation reaches a shell,
 * so user-supplied flags can't shell-inject.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  realpathSync,
  renameSync,
  statSync,
  openSync,
  readSync,
  closeSync,
  writeFileSync,
} from 'node:fs';
import { spawn, execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { dirname, extname, isAbsolute, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DOCGEN_MODEL } from '../models.mjs';

// ─── config ───────────────────────────────────────────────────────────────

/** The filename docgen OWNS and writes. Deliberately NOT `README.md` so
 *  docgen's generated output never collides with a hand-authored
 *  `README.md` — humans own README.md, docgen owns AUTO_DOCS.md. Every
 *  own-output read/write (the pyramid: prior version, parent/child docs,
 *  the embedded inputs-hash skip) targets this name. */
export const DOC_FILENAME = 'AUTO_DOCS.md';

const MARKER =
  '<!-- auto-generated by docgen — do not hand-edit. Run `tools/docgen/docgen` to refresh. -->';

/** A short prefix of the marker — used to recognise auto-gen READMEs
 *  without being tripped up by cosmetic re-wording of the full marker. */
const MARKER_DETECT_PREFIX = '<!-- auto-generated by docgen';

/** Dir-name skips (any directory at any depth named these is pruned). */
const SKIP_DIRS = new Set([
  'node_modules',
  '.git',
  'dist',
  'build',
  '.tooling',
  '.docgen',
  '.next',
  '.cache',
  'coverage',
  '__pycache__',
  '.venv',
  'venv',
  '.pytest_cache',
  '.turbo',
  '.parcel-cache',
  // Cargo/Rust build output. Belt-and-braces: the gitignore walk above is the
  // real guard, but this holds in a non-git checkout too.
  'target',
]);

/** File extension skips (binary / lock / huge). The actual size cap below
 *  catches anything we missed by extension. */
const SKIP_FILE_EXT = new Set([
  '.lock', '.lockb',
  '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.webp',
  '.pdf', '.zip', '.tar', '.gz', '.bz2', '.xz', '.7z',
  '.mp3', '.mp4', '.mov', '.wav', '.webm',
  '.bin', '.wasm', '.so', '.dylib', '.dll', '.exe',
  '.ttf', '.otf', '.woff', '.woff2', '.eot',
]);

/** Per-file cap for the prompt. Larger files get truncated with a marker
 *  so the LLM knows it's not the full content. */
const MAX_FILE_BYTES_FOR_PROMPT = 8 * 1024;
/** Skip individual files larger than this even after truncation. */
const MAX_FILE_BYTES_HARD = 1024 * 1024;
/** Skip a directory entirely only past this many files — a pathological case
 *  (thousands of generated siblings), not merely a big source directory.
 *  Ordinary generated-asset dirs are pruned by the data-only check in
 *  needsAnalysis; SIZE is bounded by MAX_CONTEXT_BYTES below, not by refusing
 *  to document the directory at all. */
export const MAX_FILES_HARD_SKIP = 400;

/** Byte budget for file BODIES in one prompt. Past this, remaining files are
 *  listed by NAME ONLY so the generated `## Map` can still point at them.
 *  ~400KB of bodies measured at roughly $1.00 per call on Sonnet — the ceiling
 *  is a cost decision, so it is stated in bytes rather than hidden in a file
 *  count. */
export const MAX_CONTEXT_BYTES = 400 * 1024;

/** Non-code file extensions. A directory whose EVERY file has one of these
 *  (and has no documented children) has no code symbols to map, so
 *  needsAnalysis skips it.
 *
 *  Covers DATA (.json/.csv/…) AND PROSE/markup (.md/.rst/…): a research
 *  output dir of `hypothesis.md` + `status.json`, or a pure docs dir,
 *  has nothing to point an agent at — and such dirs are exactly what
 *  explode docgen on data-heavy repos (this repo would otherwise queue
 *  ~12k of them under generated-data/). `.sql` STAYS documentable. */
const DATA_EXTENSIONS = new Set([
  // data
  '.json', '.jsonl', '.ndjson',
  '.csv', '.tsv',
  '.txt', '.xml',
  '.yaml', '.yml',
  '.toml', '.ini',
  '.geojson',
  '.parquet',
  // prose / markup (no code symbols to point at)
  '.md', '.markdown', '.rst', '.adoc', '.html', '.htm',
]);

/** Curated-context filenames (see collectCuratedContext for behavior).
 *  Maintainers drop these to inject hand-written guidance into the
 *  prompt without putting hand-written content inside the generated
 *  README itself (which keeps the README cleanly regeneratable). */
const CTX_GLOBAL_PATH = '.docgen/global.md';
const CTX_LOCAL_FILENAME = '.docgen-context.md';
const CTX_CASCADE_FILENAME = '.docgen-cascade.md';
/** Cap per-context-file bytes folded into the prompt. */
const MAX_CTX_BYTES = 4 * 1024;

const DEFAULT_TIMEOUT_MS = 5 * 60 * 1000;

// Per-directory READMEs are the highest-VOLUME LLM call in the toolkit
// (one per dir — hundreds on a big repo) and a comparatively simple task
// ("what's in this folder, what do these files do"). Sonnet handles it
// well at ~3-5x less than Opus, so it's the default. Override with
// `--model <name>`. (systems-registry keeps the cross-system manifest
// generation on Opus — that's the higher-judgment, lower-volume work.)
export const DEFAULT_MODEL = DOCGEN_MODEL;

// How many times to (re)generate a directory's doc before giving up. The model
// occasionally returns meta-narration instead of the doc (the trunk-doc bug);
// generation is stochastic, so a retry usually recovers. See analyzeOne.
const DEFAULT_GEN_ATTEMPTS = 3;

// ─── repo + state ─────────────────────────────────────────────────────────

function repoRoot() {
  // Allow override for tests so we don't touch the real repo.
  if (process.env.DOCGEN_REPO_ROOT) return resolve(process.env.DOCGEN_REPO_ROOT);
  try {
    // execFileSync — no shell, fixed argv. Output is the abs path of the
    // enclosing git worktree (or throws if not in one).
    return execFileSync('git', ['rev-parse', '--show-toplevel'], {
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return resolve('.');
  }
}

function statePath(root) {
  return join(root, '.docgen', 'state.json');
}

export function loadState(root) {
  const p = statePath(root);
  if (!existsSync(p)) return { version: 2, lastRun: null, directories: {} };
  try {
    const raw = readFileSync(p, 'utf8');
    const parsed = JSON.parse(raw);
    // v2 = content-hash staleness. v1 was mtime-based; we drop v1
    // silently — old states force a one-time re-bootstrap, which is
    // the price of making state durable across fresh clones.
    if (parsed && parsed.version === 2 && parsed.directories) return parsed;
  } catch {
    /* fall through */
  }
  return { version: 2, lastRun: null, directories: {} };
}

export function saveState(root, state) {
  const p = statePath(root);
  mkdirSync(dirname(p), { recursive: true });
  // Sort directories for stable diffs.
  const sorted = {
    version: state.version,
    lastRun: state.lastRun,
    directories: Object.fromEntries(
      Object.entries(state.directories).sort(([a], [b]) => a.localeCompare(b)),
    ),
  };
  writeFileSync(p, JSON.stringify(sorted, null, 2) + '\n');
}

/**
 * Serialise concurrent state writes. With `--parallel N` we can have N
 * analyzeOne calls in flight; without this, the LAST writer would lose
 * any entries the others wrote between its loadState and saveState. Each
 * caller appends to a single shared promise chain; the chain's body
 * always re-reads from disk before merging, so two concurrent writers
 * don't clobber each other.
 */
let _saveChain = Promise.resolve();
export function saveStateMerging(root, additions, lastRun) {
  _saveChain = _saveChain.then(() => {
    const state = loadState(root);
    if (lastRun) state.lastRun = lastRun;
    Object.assign(state.directories, additions);
    saveState(root, state);
  });
  return _saveChain;
}

// ─── directory walking ────────────────────────────────────────────────────

/**
 * Yield directories under root that have at least one regular file OR
 * subdirectories. Trunk directories (only sub-dirs, no files) are
 * included so they can be documented as overview/orchestration layers
 * once their children have READMEs; they would otherwise have no entry
 * point for an agent navigating top-down.
 *
 * Skips SKIP_DIRS at any depth and hidden directories.
 */
/**
 * Directories git is already ignoring, as absolute paths.
 *
 * Build output is the single biggest source of wasted generation, and every
 * ecosystem names its build dir differently — `target/`, `.next/`, `out/`,
 * `_build/`. `.gitignore` is the declaration that already exists, so honouring
 * it generalises where a hand-maintained SKIP_DIRS list cannot: a real priming
 * run spent 6 of its first 21 calls documenting Rust incremental-build blobs
 * under `target/debug/incremental/`.
 *
 * One `git` call for the whole walk. Returns an empty set outside a repo, or
 * if git is unavailable, so behaviour degrades to the old SKIP_DIRS list.
 */
export function ignoredDirs(root) {
  try {
    const out = execFileSync(
      'git',
      ['ls-files', '--others', '--ignored', '--directory', '--exclude-standard'],
      { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, stdio: ['ignore', 'pipe', 'ignore'] },
    );
    const set = new Set();
    for (const line of out.split('\n')) {
      const rel = line.trim().replace(/\/$/, '');
      if (rel) set.add(resolve(root, rel));
    }
    return set;
  } catch {
    return new Set();
  }
}

export function* walkDirs(root) {
  const ignored = ignoredDirs(root);
  const stack = [root];
  while (stack.length > 0) {
    const dir = stack.pop();
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    const subdirs = [];
    let hasFiles = false;
    let hasUsableSubdirs = false;
    for (const e of entries) {
      if (e.name === '.' || e.name === '..') continue;
      // Hidden dirs (except .github which often has CI we care about).
      if (e.name.startsWith('.') && e.name !== '.github') continue;
      if (SKIP_DIRS.has(e.name)) continue;
      if (e.isDirectory()) {
        const full = join(dir, e.name);
        if (ignored.has(full)) continue; // git already says this is not source
        subdirs.push(full);
        hasUsableSubdirs = true;
      } else if (e.isFile()) hasFiles = true;
    }
    if (hasFiles || hasUsableSubdirs) yield dir;
    // Reverse so depth-first order matches lexical order on output.
    for (let i = subdirs.length - 1; i >= 0; i--) stack.push(subdirs[i]);
  }
}

/** sha256 of a file's content, hex-encoded. Cheap (~ms per file at
 *  typical source-file sizes). Returns null on read failure so the
 *  caller treats it as "unable to verify" and skips. */
function fileContentHash(path) {
  try {
    const data = readFileSync(path);
    return createHash('sha256').update(data).digest('hex');
  } catch {
    return null;
  }
}

/** Pick the files in `dir` we'll feed to claude. Sorted by name for
 *  deterministic prompts. Each entry carries a content hash used by
 *  needsAnalysis for staleness — content hash survives fresh clones,
 *  unlike mtime which gets rewritten on checkout. */
/** How far into a file we look for a generated-marker. */
export const GENERATED_MARKER_WINDOW = 2048;

/**
 * True when a file announces itself as machine-generated.
 *
 * `@generated` is the de-facto convention (Meta, Bazel, protoc, and our own
 * autodocs mirrors all emit it). Only the head of the file counts, so a
 * document merely *discussing* the convention does not exclude itself.
 */
export function isGeneratedFile(full) {
  let fd;
  try {
    fd = openSync(full, 'r');
    const buf = Buffer.alloc(GENERATED_MARKER_WINDOW);
    const n = readSync(fd, buf, 0, GENERATED_MARKER_WINDOW, 0);
    return buf.subarray(0, n).toString('utf8').includes('@generated');
  } catch {
    return false;
  } finally {
    if (fd !== undefined) {
      try {
        closeSync(fd);
      } catch {
        /* already closed */
      }
    }
  }
}

export function selectFiles(dir) {
  const out = [];
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    if (!e.isFile()) continue;
    // We OWN AUTO_DOCS.md — don't feed our own output back in.
    if (e.name === DOC_FILENAME) continue;
    // README.md is human-owned and invisible to docgen — don't read it
    // into the prompt either (it sits alongside AUTO_DOCS.md, ignored).
    if (e.name === 'README.md') continue;
    if (SKIP_FILE_EXT.has(extname(e.name).toLowerCase())) continue;
    if (e.name.startsWith('.')) continue;
    const full = join(dir, e.name);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (st.size > MAX_FILE_BYTES_HARD) continue;
    // Generated files are OUTPUT, not source. Reading one back in makes it part
    // of this directory's inputs hash, so the directory can never settle:
    // regenerate -> the generated file is rewritten -> the hash changes ->
    // regenerate, forever. Ownership is decided by the marker, not the
    // filename, so a hand-written CLAUDE.md stays a legitimate input.
    if (isGeneratedFile(full)) continue;
    const hash = fileContentHash(full);
    if (!hash) continue; // unreadable; skip
    out.push({ name: e.name, full, hash, size: st.size });
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}

/**
 * walkDirs sorted by depth descending (deepest first), with lexical
 * secondary order. Bottom-up traversal lets us generate child READMEs
 * before parents that summarise them, which is the entire point of the
 * pyramid: a parent's prompt context can include its children's
 * already-generated READMEs (one paragraph each) instead of the
 * children's raw files (kilobytes each).
 */
export function walkDirsBottomUp(root) {
  const all = [...walkDirs(root)];
  return all.sort((a, b) => {
    const depthDiff = b.split('/').length - a.split('/').length;
    return depthDiff !== 0 ? depthDiff : a.localeCompare(b);
  });
}

/**
 * Expand a list of paths (file paths OR directory paths) into the set
 * of directories that includes them AND every ancestor directory up to
 * (but not above) `root`. Used by --scope to keep trunk bubble-up
 * working: if a file in `services/api/` changed, the parent trunks
 * `services/api/` and `services/` may also need refreshing because their child
 * versions may have bumped.
 *
 * Inputs:
 *   - paths: absolute or repo-relative paths (files or dirs)
 *   - root:  repo root (absolute, canonicalised)
 *
 * Returns: Set of absolute paths inside `root`. Paths outside `root`
 * are silently dropped.
 */
export function expandScopeWithAncestors(root, paths) {
  const out = new Set();
  const canonicalRoot = root;
  for (const p of paths) {
    if (!p) continue;
    let abs = isAbsolute(p) ? p : resolve(root, p);
    // If `abs` is a file, start from its parent dir. If it's a dir
    // (or doesn't exist — e.g. removed by the diff), use it directly.
    let dir;
    try {
      const st = existsSync(abs) ? statSync(abs) : null;
      dir = st && st.isFile() ? dirname(abs) : abs;
    } catch {
      dir = abs;
    }
    // Walk up until we leave the repo root.
    let current = dir;
    while (
      current === canonicalRoot ||
      (current.startsWith(canonicalRoot + '/') && current.length > canonicalRoot.length)
    ) {
      out.add(current);
      if (current === canonicalRoot) break;
      const parent = dirname(current);
      if (parent === current) break;
      current = parent;
    }
  }
  return out;
}

/**
 * Find immediate sub-directories of `dir` that already have a generated
 * AUTO_DOCS.md + version in state. Returned list is what feeds the "you
 * are a trunk; summarise these children" prompt context.
 */
export function findChildReadmesInState(root, dir, state) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }
  const out = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (e.name.startsWith('.') && e.name !== '.github') continue;
    if (SKIP_DIRS.has(e.name)) continue;
    const subFull = join(dir, e.name);
    const subRel = relative(root, subFull);
    const subEntry = state.directories[subRel];
    if (!subEntry?.version) continue;
    const subReadmePath = join(subFull, DOC_FILENAME);
    if (!existsSync(subReadmePath)) continue;
    try {
      out.push({
        relPath: subRel,
        version: subEntry.version,
        content: readFileSync(subReadmePath, 'utf8'),
      });
    } catch { /* ignore */ }
  }
  out.sort((a, b) => a.relPath.localeCompare(b.relPath));
  return out;
}

/**
 * Does `docPath` carry docgen's auto-gen marker? Used by `migrate` to
 * tell a docgen-authored README.md (rename it → AUTO_DOCS.md) apart from
 * a hand-authored one (leave it alone). docgen no longer "protects"
 * hand-written READMEs in its walk — it owns AUTO_DOCS.md, a separate
 * filename — so this is only consulted by the migration path.
 */
export function hasDocgenMarker(docPath) {
  if (!existsSync(docPath)) return false;
  try {
    const head = readFileSync(docPath, 'utf8').slice(0, 512);
    return head.trimStart().startsWith(MARKER_DETECT_PREFIX);
  } catch {
    return false;
  }
}

// ─── version handling (semver-flavoured) ──────────────────────────────────

const VERSION_RE = /<!--\s*docgen:version=(\d+)\.(\d+)\.(\d+)(?:\s+reason:\s*([^>]*?))?\s*-->/;

/**
 * Parse `<!-- docgen:version=X.Y.Z reason: ... -->` out of a string.
 * Returns `{ version, reason, raw }` or `null` if not found.
 */
export function parseVersion(text) {
  if (!text) return null;
  const m = (text || '').match(VERSION_RE);
  if (!m) return null;
  return {
    version: `${m[1]}.${m[2]}.${m[3]}`,
    reason: (m[4] ?? '').trim() || null,
    raw: m[0],
  };
}

// ─── portable inputs-hash (cross-clone / cross-worktree skip) ───────────────

const INPUTS_HASH_RE = /<!--\s*docgen:inputs=([0-9a-f]+)\s*-->/;

/**
 * Cheap structural gate: does `body` look like a docgen doc (opens with a `## `
 * heading) rather than model meta-narration ("README written at …", "The file
 * already exists … Let me compare …")? The generation prompt mandates a
 * `## Purpose`-led body, so a response with no leading heading is the model
 * narrating its own action instead of writing the doc — the trunk-doc failure
 * mode. This is a POSITIVE check (real docs have structure), so it catches every
 * phrasing rather than blocklisting known-bad prefixes. Used by analyzeOne to
 * refuse writing garbage over a good doc; kept pure + exported for testing.
 */
export function isReadmeLike(body) {
  const stripped = (body ?? '')
    .replace(MARKER, '')
    .replace(VERSION_RE, '')
    .replace(INPUTS_HASH_RE, '');
  const firstNonEmpty = stripped.split('\n').find((l) => l.trim() !== '');
  return (firstNonEmpty ?? '').trimStart().startsWith('## ');
}

/**
 * Parse `<!-- docgen:inputs=<hex> -->` out of a string. Returns the hex
 * string, or null if absent (old-format READMEs predate this marker).
 */
export function parseInputsHash(text) {
  if (!text) return null;
  const m = (text || '').match(INPUTS_HASH_RE);
  return m ? m[1] : null;
}

/**
 * Deterministic, PORTABLE hash of everything that feeds a directory's
 * generated README — the inputs, NOT the body. Embedding it in the
 * committed README lets `needsAnalysis` skip a dir on a machine that has
 * NO `.docgen/state.json` (fresh clone, fresh worktree): if the README's
 * embedded hash equals the freshly-recomputed hash, the inputs are
 * unchanged and the committed README is already current.
 *
 * What goes in (all sorted for determinism):
 *   - own files: `name` + content `hash` (selectFiles already gives the
 *     sha256 content hash — content survives checkout, mtime does not).
 *   - child READMEs: `relPath` + full `version`. needsAnalysis only
 *     cascades a child's MAJOR bump, but hashing the FULL version here is
 *     deliberately stricter: a minor/patch child change re-triggers the
 *     parent via the hash, which is safe (over-regenerates at worst) and
 *     keeps this helper simple + obviously correct.
 *   - curated context: `relPath` + a CONTENT hash of each file. State
 *     keys curated context off mtime; mtime is NOT portable (a fresh
 *     clone rewrites every mtime to checkout time), so we hash content
 *     instead — that's the whole point of making this durable.
 *
 * The README BODY is intentionally excluded, so writing this hash into
 * the README does not change the hash (write-time == check-time).
 */
export function computeInputsHash({ files = [], childReadmes = [], curatedContext = [] } = {}) {
  const h = createHash('sha256');
  const ownFiles = [...files]
    .map((f) => ({ name: f.name, hash: f.hash }))
    .sort((a, b) => a.name.localeCompare(b.name));
  h.update('files\n');
  for (const f of ownFiles) h.update(`${f.name} ${f.hash}\n`);

  const children = [...childReadmes]
    .map((c) => ({ relPath: c.relPath, version: c.version }))
    .sort((a, b) => a.relPath.localeCompare(b.relPath));
  h.update('children\n');
  for (const c of children) h.update(`${c.relPath} ${c.version}\n`);

  const ctx = [...curatedContext]
    .map((c) => ({
      relPath: c.relPath,
      hash: createHash('sha256').update(c.content ?? '').digest('hex'),
    }))
    .sort((a, b) => a.relPath.localeCompare(b.relPath));
  h.update('context\n');
  for (const c of ctx) h.update(`${c.relPath} ${c.hash}\n`);

  // 16 hex chars (64 bits) — collision-resistant at repo scale, short
  // enough to keep the README header tidy.
  return h.digest('hex').slice(0, 16);
}

/** Read prior version from `<dir>/AUTO_DOCS.md` (if any). */
export function priorVersion(dir) {
  const p = join(dir, DOC_FILENAME);
  if (!existsSync(p)) return null;
  try {
    const head = readFileSync(p, 'utf8').slice(0, 2 * 1024);
    return parseVersion(head)?.version ?? null;
  } catch {
    return null;
  }
}

/**
 * Classify a version transition as patch/minor/major/same/initial.
 * Compares `prev` to `next` ; either may be null/undefined.
 */
export function bumpType(prev, next) {
  if (!prev && next) return 'initial';
  if (!prev && !next) return 'initial';
  if (!next) return 'same';
  const [pM, pm, pp] = prev.split('.').map(Number);
  const [nM, nm, np] = next.split('.').map(Number);
  if (nM !== pM) return 'major';
  if (nm !== pm) return 'minor';
  if (np !== pp) return 'patch';
  return 'same';
}

/**
 * Resolve the final version to write. Inputs:
 *   - priorV: version of the prior README (or null)
 *   - llmV: version the LLM declared in its output (or null)
 *   - fileSetChanged: whether files were added/removed since priorV
 *
 * Policy:
 *   - If no prior, accept LLM's declared version, defaulting to '0.1.0'.
 *   - If LLM didn't declare a version, fall back to a patch bump.
 *   - If the LLM declared a patch bump BUT files were added/removed,
 *     escalate to minor — the LLM's judgement is overridable here so a
 *     genuine structural change can't be silently labelled cosmetic.
 *   - Otherwise honour the LLM's version.
 */
export function resolveVersion(priorV, llmV, fileSetChanged) {
  if (!priorV) return llmV ?? '0.1.0';
  if (!llmV) {
    const [M, m, p] = priorV.split('.').map(Number);
    return `${M}.${m}.${p + 1}`;
  }
  if (fileSetChanged && bumpType(priorV, llmV) === 'patch') {
    const [M, m] = priorV.split('.').map(Number);
    return `${M}.${m + 1}.0`;
  }
  return llmV;
}

// ─── staleness ────────────────────────────────────────────────────────────

/**
 * Reason a directory needs (re)analysis, or null if fresh. Three kinds
 * of staleness:
 *   - own file-set / mtime drift (this dir's own files changed),
 *   - child README crossed a minor-or-major boundary since we last
 *     looked (a sub-directory's responsibilities materially changed),
 *   - a new child README appeared that wasn't there when we were last
 *     analysed (new sub-directory landed under us).
 *
 * Pure cosmetic (patch) bumps in children DO NOT propagate. That's the
 * cost optimisation; without it, one leaf edit re-generates every
 * ancestor up to the repo root.
 */
export function needsAnalysis(root, dir, state) {
  const rel = relative(root, dir) || '.';
  const entry = state.directories[rel];
  const files = selectFiles(dir);
  const childReadmes = findChildReadmesInState(root, dir, state);
  // Nothing to document — no own files, no documented children.
  if (files.length === 0 && childReadmes.length === 0) return null;
  // Pathological dirs only. This used to be `> MAX_FILES_PER_DIR` (60), which
  // silently skipped the most important directories in a real repo:
  // pbx-platform's apps/control-plane/src has 236 hand-written modules and is
  // the most-churned directory in that codebase, and it could never be
  // regenerated at any price — while still reporting as documented.
  //
  // Generated-asset dirs are caught by the data-only check just below, which
  // is what actually prunes them. Size is handled where it belongs, in
  // assembleContext's byte budget, so a large SOURCE dir gets a doc that names
  // every file even when it cannot include every body.
  if (files.length > MAX_FILES_HARD_SKIP) return null;
  // No-code skip: a dir whose every file is data OR prose/markup (no code
  // symbols to point an agent at) is skipped — UNLESS it has documented
  // children, in which case it acts as a trunk and still gets a README.
  // Critical on this repo: prunes ~11.8k generated-data/items/<id>
  // dirs (each is hypothesis.md + status.json) that would otherwise burn
  // thousands of `claude -p` calls.
  if (
    files.length > 0 &&
    files.every((f) => DATA_EXTENSIONS.has(extname(f.name).toLowerCase())) &&
    childReadmes.length === 0
  ) return null;
  // NOTE: docgen owns AUTO_DOCS.md — a hand-written README.md in this dir
  // is invisible and does NOT block generating an AUTO_DOCS.md here. (The
  // old "skip if README.md is hand-written" guard is gone; docgen's output
  // lives at a filename it controls, so there's nothing to protect.)
  const docPath = join(dir, DOC_FILENAME);

  // Cross-machine skip (the token fix). `.docgen/state.json` is gitignored,
  // so a fresh clone / fresh worktree starts with NO state → every dir
  // would otherwise return 'never-analyzed' and regenerate docs that are
  // already committed and current. To avoid that waste, the generated
  // AUTO_DOCS.md carries a portable inputs-hash in its header. If a
  // docgen-generated AUTO_DOCS.md exists and its embedded hash equals the
  // freshly-computed hash of THIS dir's inputs, the committed doc is
  // current regardless of whether state exists → skip.
  //
  // An old-format AUTO_DOCS.md (no embedded hash) returns null from
  // parseInputsHash and falls through to the existing behavior below
  // (regenerates once when state is absent, then gains the hash). Pure
  // predicate: we read the doc but never write state from here.
  if (existsSync(docPath)) {
    try {
      const embedded = parseInputsHash(readFileSync(docPath, 'utf8'));
      if (embedded) {
        const curatedContext = collectCuratedContext(root, dir);
        const current = computeInputsHash({ files, childReadmes, curatedContext });
        if (embedded === current) return null;
      }
    } catch { /* unreadable — fall through to state-based logic */ }
  }

  if (!entry) return 'never-analyzed';

  // A state entry with NO doc on disk is stale, not fresh.
  //
  // The existsSync above is only a fast-path SKIP. Without this, a dir whose
  // files have not changed since its entry was written reported fresh whether
  // or not the doc actually existed — so a deleted doc never came back, and a
  // dir left over from the README.md -> AUTO_DOCS.md rename stayed invisible
  // permanently. Measured on pbx-platform: 173 of 335 entries had no doc, ALL
  // of them reported fresh, and computeStatus said `uncovered=0` while 52% of
  // the tree was undocumented. `--until-done` only visits what needsAnalysis
  // flags, so no runner — local or CI — could ever reach them.
  if (!existsSync(docPath)) return 'doc-missing';

  // Own-file checks.
  const prev = entry.files || {};
  const curNames = files.map((f) => f.name).sort();
  const prevNames = Object.keys(prev).sort();
  if (curNames.length !== prevNames.length) return 'file-set-changed';
  for (let i = 0; i < curNames.length; i++) {
    if (curNames[i] !== prevNames[i]) return 'file-set-changed';
  }
  for (const f of files) {
    if ((prev[f.name] ?? '') !== f.hash) {
      return 'file-modified';
    }
  }

  // Child-version checks. Only a child's MAJOR bump cascades up to its
  // parent — minor AND patch bumps stay local. Per prompt.md's version
  // semantics a MAJOR bump means the child's purpose changed or it was
  // restructured top-to-bottom (its old README is "essentially obsolete")
  // — so the one-line summary the parent's index carries for that child
  // is now wrong too, and the parent must be re-generated. A minor bump
  // (new file, a responsibility moved, a renamed function) or a patch
  // (cosmetic) leaves the parent's index-level description of the child
  // still accurate, so re-generating the whole ancestor chain for it is
  // needless cost. (A newly-added or removed child still always
  // re-triggers the parent — see below.)
  const recordedChildren = entry.childVersionsAtAnalysis || {};
  for (const c of childReadmes) {
    const recorded = recordedChildren[c.relPath];
    if (!recorded) return `child-added:${c.relPath}`;
    const [rM] = recorded.split('.').map(Number);
    const [cM] = c.version.split('.').map(Number);
    if (rM !== cM) return `child-bumped:${c.relPath}`;
  }
  // A child we previously summarised has disappeared (dir removed).
  for (const recordedRel of Object.keys(recordedChildren)) {
    if (!childReadmes.some((c) => c.relPath === recordedRel)) {
      return `child-removed:${recordedRel}`;
    }
  }
  // Curated-context file checks. Any new file, mtime bump, or removed
  // file triggers a re-generation.
  const recordedCtx = entry.curatedContextAtAnalysis || {};
  const currentCtx = collectCuratedContext(root, dir);
  for (const c of currentCtx) {
    const recorded = recordedCtx[c.relPath];
    if (recorded === undefined) return `context-added:${c.relPath}`;
    if (Math.floor(recorded) !== Math.floor(c.mtimeMs)) {
      return `context-modified:${c.relPath}`;
    }
  }
  for (const recordedRel of Object.keys(recordedCtx)) {
    if (!currentCtx.some((c) => c.relPath === recordedRel)) {
      return `context-removed:${recordedRel}`;
    }
  }
  return null;
}

// ─── claude subprocess ────────────────────────────────────────────────────

/** Default claude runner. Pass a mock via `analyzeOne({ runner })` in
 *  tests. spawn() with array args — no shell interpolation. */
function defaultRunner({ prompt, context, model, timeoutMs = DEFAULT_TIMEOUT_MS }) {
  return new Promise((resolveP, rejectP) => {
    const args = ['-p', '--output-format', 'text'];
    if (model) args.push('--model', model);
    const proc = spawn('claude', args, { stdio: ['pipe', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    let settled = false;
    const settle = (fn) => {
      if (!settled) {
        settled = true;
        fn();
      }
    };
    const timer = setTimeout(() => {
      try { proc.kill('SIGTERM'); } catch { /* gone */ }
      settle(() => rejectP(new Error(`docgen: claude timed out after ${timeoutMs}ms`)));
    }, timeoutMs);
    proc.stdout.on('data', (d) => (stdout += d.toString()));
    proc.stderr.on('data', (d) => (stderr += d.toString()));
    proc.on('error', (err) => {
      clearTimeout(timer);
      settle(() => rejectP(new Error(
        err.code === 'ENOENT'
          ? 'docgen: claude CLI not on PATH — install with: npm install -g @anthropic-ai/claude-code'
          : `docgen: claude spawn error: ${err.message}`,
      )));
    });
    proc.on('exit', (code) => {
      clearTimeout(timer);
      settle(() => {
        if (code === 0) { resolveP(stdout); return; }
        const err = new Error(`docgen: claude exited ${code}: ${stderr.slice(0, 500)}`);
        // Detect "cwd was deleted" — claude itself checks its own cwd
        // before running and bails. Every subsequent call from a
        // --until-done loop would fail the same way, so flag fatal so
        // the outer loop halts instead of grinding forever (the
        // runaway-zombie class of bug seen with worktree cleanup).
        if (/current working directory was deleted|cwd .* deleted/i.test(stderr)) {
          err.code = 'CWD_DELETED';
          err.halt = true;
        }
        rejectP(err);
      });
    });
    proc.stdin.on('error', () => {});
    try {
      proc.stdin.write(prompt + '\n\n--- CONTEXT ---\n\n' + context);
      proc.stdin.end();
    } catch {
      /* error/exit will reject */
    }
  });
}

// ─── prompt assembly ──────────────────────────────────────────────────────

function loadPrompt(scriptDir) {
  return readFileSync(join(scriptDir, 'prompt.md'), 'utf8');
}

/**
 * Assemble the context string the LLM sees: a header naming the dir,
 * the prior version (if any), the parent README (for vocabulary),
 * any already-generated child READMEs (for trunk dirs — these turn
 * the LLM into a summariser, not a re-grepper), and every selected
 * file as a fenced block. Files over the per-file cap are truncated.
 */
/**
 * Collect curated-context items for a directory's prompt. Returns an
 * array of `{label, content, relPath, mtimeMs}` in priority order:
 *
 *   1. Global  — `<root>/.docgen/global.md` (every prompt)
 *   2. Local   — `<dir>/.docgen-context.md` (only this dir's prompt)
 *   3. Cascade — every `<descendant>/.docgen-cascade.md` (bubbles up)
 *
 * The bubble-up pattern is the load-bearing one: a single
 * `.docgen-cascade.md` at `services/scripts/build/factory/` (e.g.
 * "available commands at this layer") flows into the prompts of
 * every ancestor (`build/`, `scripts/`, `services/`, `.`), so the
 * generated README at each level naturally surfaces the same vocab.
 *
 * Each entry's `relPath` + `mtimeMs` is also persisted into state so
 * `needsAnalysis` can re-trigger a re-generation when a context file
 * changes — same shape as the existing per-file mtime tracking.
 */
export function collectCuratedContext(root, dir) {
  const items = [];

  const globalPath = join(root, CTX_GLOBAL_PATH);
  if (existsSync(globalPath)) {
    items.push({
      label: 'Global context (.docgen/global.md)',
      content: readFileSync(globalPath, 'utf8').slice(0, MAX_CTX_BYTES),
      relPath: relative(root, globalPath),
      mtimeMs: statSync(globalPath).mtimeMs,
    });
  }

  const localPath = join(dir, CTX_LOCAL_FILENAME);
  if (existsSync(localPath)) {
    items.push({
      label: `Local context (${relative(root, localPath)})`,
      content: readFileSync(localPath, 'utf8').slice(0, MAX_CTX_BYTES),
      relPath: relative(root, localPath),
      mtimeMs: statSync(localPath).mtimeMs,
    });
  }

  // Cascade: every descendant's .docgen-cascade.md bubbles into this
  // dir's prompt. Reuses walkDirs so we get the same SKIP_DIRS filter
  // (no node_modules, no .git, etc.).
  for (const descendant of walkDirs(dir)) {
    const cascadePath = join(descendant, CTX_CASCADE_FILENAME);
    if (!existsSync(cascadePath)) continue;
    items.push({
      label: `Cascade context (${relative(root, cascadePath)})`,
      content: readFileSync(cascadePath, 'utf8').slice(0, MAX_CTX_BYTES),
      relPath: relative(root, cascadePath),
      mtimeMs: statSync(cascadePath).mtimeMs,
    });
  }

  return items;
}

export function assembleContext(root, dir, files, opts = {}) {
  const { childReadmes = [], priorVersionStr = null, curatedContext = [] } = opts;
  const rel = relative(root, dir) || '.';
  const lines = [`# Directory: ${rel}`, ''];

  if (priorVersionStr) {
    lines.push(`## Prior version of this README`);
    lines.push('');
    lines.push(`The previous README declared version \`${priorVersionStr}\`.`);
    lines.push(
      'Bump patch / minor / major versus this baseline per the rules in your instructions.',
    );
    lines.push('');
  } else {
    lines.push('## Prior version of this README');
    lines.push('');
    lines.push('No prior README — this is the first generation. Start at `0.1.0`.');
    lines.push('');
  }
  // Curated context — hand-written guidance the maintainer wants the
  // LLM to treat as authoritative. See collectCuratedContext for the
  // three sources (global / local / cascade). Placed BEFORE child
  // READMEs + raw files so the LLM frames the generated content
  // around maintainer intent rather than re-deriving from scratch.
  if (curatedContext.length > 0) {
    lines.push('## Curated context (hand-written, treat as authoritative)');
    lines.push('');
    for (const item of curatedContext) {
      lines.push(`### ${item.label}`);
      lines.push('');
      lines.push(item.content.trimEnd());
      lines.push('');
    }
  }


  // Parent AUTO_DOCS.md for vocabulary continuity.
  const parentReadme = join(dirname(dir), DOC_FILENAME);
  if (parentReadme !== join(dir, DOC_FILENAME) && existsSync(parentReadme)) {
    try {
      const txt = readFileSync(parentReadme, 'utf8');
      lines.push(`## Parent directory AUTO_DOCS.md (for context only)`);
      lines.push('');
      lines.push(txt.slice(0, 4 * 1024));
      lines.push('');
    } catch { /* ignore */ }
  }

  // Child READMEs — present iff this is a trunk dir. The LLM
  // SUMMARISES these in the new ## Subdirectories section; it does NOT
  // re-derive their detail from raw files.
  if (childReadmes.length > 0) {
    lines.push(
      `## Already-generated child READMEs (${childReadmes.length}) — summarise, do NOT duplicate`,
    );
    lines.push('');
    for (const c of childReadmes) {
      lines.push(`### Subdirectory: ${c.relPath}  (version ${c.version})`);
      lines.push('');
      lines.push(c.content.slice(0, 4 * 1024));
      lines.push('');
    }
  }

  lines.push(`## Files directly in this directory (${files.length})`);
  lines.push('');

  // Spend the byte budget on bodies, smallest first: for a given budget that
  // maximises how many files the model actually reads, and the big files that
  // miss out are the ones most likely to be generated or vendored anyway.
  const budgetOrder = [...files].sort((a, b) => (a.size || 0) - (b.size || 0));
  const included = new Set();
  let spent = 0;
  for (const f of budgetOrder) {
    if (spent >= MAX_CONTEXT_BYTES) break;
    let body;
    try {
      body = readFileSync(f.full, 'utf8');
    } catch {
      continue;
    }
    let truncated = false;
    if (body.length > MAX_FILE_BYTES_FOR_PROMPT) {
      body = body.slice(0, MAX_FILE_BYTES_FOR_PROMPT);
      truncated = true;
    }
    spent += body.length;
    included.add(f.name);
    const ext = extname(f.name).slice(1) || '';
    lines.push(`### ${f.name}${truncated ? ' (truncated)' : ''}`);
    lines.push('```' + ext);
    lines.push(body.trimEnd());
    lines.push('```');
    lines.push('');
  }

  // Everything the budget could not fit still gets NAMED, so the generated
  // `## Map` can point an agent at it. A map missing a file is a map that
  // quietly lies about what lives here.
  const omitted = files.filter((f) => !included.has(f.name));
  if (omitted.length > 0) {
    lines.push(
      `### Remaining ${omitted.length} file(s) — listed by name only (prompt budget reached)`,
    );
    lines.push('');
    lines.push(
      'Their contents are NOT shown. Still reference them in the Map by name ' +
        'where the name makes their responsibility clear; do not invent detail ' +
        'about what is inside them.',
    );
    lines.push('');
    for (const f of omitted) lines.push(`- \`${f.name}\` (${f.size} bytes)`);
    lines.push('');
  }
  return lines.join('\n');
}

// ─── analysis core ────────────────────────────────────────────────────────

/** True when the failure looks like "the file/dir we're operating on
 *  vanished" — covers the short-lived-worktree cleanup race that
 *  hits when another tool spawns + tears down a temp clone faster
 *  than the detached docgen background process can finish. */
function isVanishedPathError(err) {
  if (!err || typeof err !== 'object') return false;
  return err.code === 'ENOENT' || err.code === 'ENOTDIR' || err.code === 'EACCES';
}

export async function analyzeOne(root, opts = {}) {
  const {
    runner = defaultRunner,
    promptText,
    forceDir = null,
    model,
    timeoutMs,
    dryRun = false,
    maxGenAttempts = DEFAULT_GEN_ATTEMPTS,
    log = () => {},
  } = opts;

  const state = loadState(root);

  // Pick the target. Bottom-up walk so a leaf is documented before its
  // trunk — that way the trunk's prompt gets the children's already-
  // generated READMEs as context instead of re-deriving from raw files.
  let target = null;
  let reason = null;
  if (forceDir) {
    target = resolve(forceDir);
    reason = 'forced';
  } else {
    for (const dir of walkDirsBottomUp(root)) {
      const r = needsAnalysis(root, dir, state);
      if (r) {
        target = dir;
        reason = r;
        break;
      }
    }
  }
  if (!target) return { picked: null };

  // Defensive: the target dir may have vanished between when the walk
  // picked it and when we run. Happens when another tool spawns a
  // short-lived worktree, kicks the pre-push hook, then deletes the
  // worktree before our detached background docgen finishes. Skip
  // cleanly so the next batch step keeps making progress.
  if (!existsSync(target)) {
    return {
      picked: relative(root, target) || '.',
      skipped: 'vanished',
      message: `target directory no longer exists (worktree cleanup race?); skipping`,
    };
  }

  const files = selectFiles(target);
  const childReadmes = findChildReadmesInState(root, target, state);
  if (files.length === 0 && childReadmes.length === 0) return { picked: null };

  const rel = relative(root, target) || '.';
  const readmePath = join(target, DOC_FILENAME);

  // No hand-written-README guard here: docgen writes AUTO_DOCS.md, a
  // filename it owns. A hand-authored README.md in the same dir is left
  // untouched. (`force` is still accepted for back-compat but is a no-op
  // now that there's nothing to refuse to overwrite.)

  const priorV = priorVersion(target);
  const curatedContext = collectCuratedContext(root, target);
  const context = assembleContext(root, target, files, {
    childReadmes,
    priorVersionStr: priorV,
    curatedContext,
  });

  if (dryRun) {
    return {
      picked: rel,
      reason,
      fileCount: files.length,
      childCount: childReadmes.length,
      priorVersion: priorV,
      dryRun: true,
    };
  }

  // Generate, guarding the trunk-doc failure mode: the model sometimes returns
  // meta-narration ("README written at …", "no changes needed …") instead of the
  // doc. Writing that verbatim was the bug. Retry a few times (generation is
  // stochastic); if EVERY attempt is non-README, refuse to write — keep a prior
  // good doc rather than clobber it, and leave the dir stale so a later run
  // retries. The batch livelock guard skips a dir that stays stale this run.
  let cleaned = null;
  for (let attempt = 1; attempt <= maxGenAttempts; attempt++) {
    const body = await runner({ prompt: promptText, context, model, timeoutMs });
    // Strip outer ```markdown fence if Claude wrapped its response.
    const candidate = stripWrappingFence(body).trim();
    if (isReadmeLike(candidate)) {
      cleaned = candidate;
      break;
    }
    log(
      `docgen: ${rel} — generation attempt ${attempt}/${maxGenAttempts} produced ` +
        `meta-narration, not a doc (no '## ' heading); ` +
        (attempt < maxGenAttempts ? 'retrying' : 'giving up'),
    );
  }
  if (cleaned === null) {
    return {
      picked: rel,
      skipped: 'invalid-generation',
      keptPrior: priorV != null,
      message:
        `model returned meta-narration, not a doc, after ${maxGenAttempts} attempts; ` +
        (priorV != null ? 'kept the prior doc' : 'no doc written'),
    };
  }

  // Extract the LLM's declared version, then resolve to the final
  // version we'll write. The LLM's choice may be overridden if the
  // file-set changed but the LLM picked patch (see resolveVersion).
  const llmVersion = parseVersion(cleaned)?.version ?? null;
  const fileSetChanged = computeFileSetChanged(state, rel, files);
  const finalVersion = resolveVersion(priorV, llmVersion, fileSetChanged);

  // Build the on-disk content: docgen MARKER, then a normalised
  // version line (regardless of what the LLM emitted — we own this),
  // then a portable inputs-hash line (lets fresh clones/worktrees skip
  // this dir without any .docgen/state.json — see needsAnalysis), then
  // the LLM's body with its own version/inputs lines stripped so we
  // don't end up with duplicates stacked.
  const versionReason =
    parseVersion(cleaned)?.reason ?? (priorV ? 'auto-generated' : 'initial generation');
  const normalisedVersionLine =
    `<!-- docgen:version=${finalVersion} reason: ${versionReason} -->`;
  // Hash is over the SAME inputs the prompt was built from (files +
  // childReadmes + curatedContext), and excludes the body, so it matches
  // what needsAnalysis recomputes at check-time.
  const inputsHash = computeInputsHash({ files, childReadmes, curatedContext });
  const inputsHashLine = `<!-- docgen:inputs=${inputsHash} -->`;
  const bodyWithoutMeta = cleaned
    .replace(VERSION_RE, '')
    .replace(INPUTS_HASH_RE, '')
    .replace(/^\s+/, '');
  const finalContent =
    `${MARKER}\n${normalisedVersionLine}\n${inputsHashLine}\n\n${bodyWithoutMeta}\n`;

  // Ensure parent exists (mkdirp) and wrap write — if the worktree was
  // partially cleaned mid-flight the leaf dir may be gone even though
  // the existsSync(target) check above passed. mkdirSync recursive is
  // a no-op when the dir already exists. ENOENT/ENOTDIR/EACCES at the
  // write site means the path is gone; skip cleanly instead of
  // crashing the whole batch.
  try {
    mkdirSync(dirname(readmePath), { recursive: true });
    writeFileSync(readmePath, finalContent);
  } catch (err) {
    if (isVanishedPathError(err)) {
      return {
        picked: rel,
        skipped: 'vanished',
        message: `path no longer writable (${err.code}); worktree likely cleaned mid-run`,
      };
    }
    throw err;
  }

  // Persist via the merging save so concurrent analyzeOne calls (with
  // `--parallel N`) don't clobber each other's entries. saveStateMerging
  // re-reads from disk inside its mutex, merges our additions, and
  // writes back.
  const newEntry = {
    lastAnalyzed: new Date().toISOString(),
    reason,
    version: finalVersion,
    files: Object.fromEntries(files.map((f) => [f.name, f.hash])),
    childVersionsAtAnalysis: Object.fromEntries(
      childReadmes.map((c) => [c.relPath, c.version]),
    ),
    curatedContextAtAnalysis: Object.fromEntries(
      curatedContext.map((c) => [c.relPath, Math.floor(c.mtimeMs)]),
    ),
  };
  await saveStateMerging(root, { [rel]: newEntry }, new Date().toISOString());

  return {
    picked: rel,
    reason,
    fileCount: files.length,
    childCount: childReadmes.length,
    priorVersion: priorV,
    llmVersion,
    finalVersion,
    fileSetChanged,
    readmePath,
    bytes: finalContent.length,
  };
}

/** Did the file set in `rel` change vs what state recorded? */
function computeFileSetChanged(state, rel, files) {
  const entry = state.directories[rel];
  if (!entry) return false; // first analysis — not a "change"
  const prev = entry.files || {};
  const curNames = files.map((f) => f.name).sort();
  const prevNames = Object.keys(prev).sort();
  if (curNames.length !== prevNames.length) return true;
  for (let i = 0; i < curNames.length; i++) {
    if (curNames[i] !== prevNames[i]) return true;
  }
  return false;
}

/** If Claude wrapped its response in a single outer ```markdown fence,
 *  strip it. Otherwise return as-is. */
function stripWrappingFence(s) {
  const trimmed = s.trim();
  const m = trimmed.match(/^```(?:markdown|md)?\s*\n([\s\S]*?)\n```\s*$/);
  return m ? m[1] : trimmed;
}

// ─── parallel orchestrator ────────────────────────────────────────────────

/**
 * Run docgen across every needs-analysis directory, parallelising
 * within depth levels. Bottom-up ordering is preserved (a trunk's
 * children are always documented first); only DIRS AT THE SAME DEPTH
 * run concurrently, because they are guaranteed to be independent —
 * siblings or unrelated branches whose subtrees were already settled
 * in earlier iterations.
 *
 * Concurrency cap: at most `parallel` analyzeOne calls in flight at
 * once, regardless of how many actionable dirs share a depth.
 *
 * Progress: `onProgress(result)` fires once per completed dir. The
 * CLI uses this to print "[N/total] wrote services/api (..)" lines
 * so a tail -f or Monitor can follow the bootstrap live.
 */
export async function analyzeAllParallel(root, opts = {}) {
  const {
    parallel = 1,
    onProgress,
    onBatchStart,
    scope,                // Set<string> of absolute dir paths, or null
    changed,              // string[] of relative dir paths (--changed flag); builds scope
    ...analyzeOpts
  } = opts;

  // When --changed is provided, build the effective scope set from those
  // relative dir paths + all their ancestor dirs up to root. This is the
  // same expansion that --scope uses; --changed is the CLI surface and
  // this is the internal plumbing.
  let effectiveScope = scope ?? null;
  if (changed && changed.length > 0 && !effectiveScope) {
    effectiveScope = new Set();
    for (const relDir of changed) {
      let abs = resolve(root, relDir);
      // Walk from the changed dir up to (and including) root.
      while (true) {
        effectiveScope.add(abs);
        if (abs === root) break;
        const parent = dirname(abs);
        if (parent === abs) break; // filesystem root guard
        abs = parent;
      }
    }
  }

  let done = 0;
  let skipped = 0;

  // Livelock guard. The outer loop re-walks the tree each iteration so a
  // freshly-written child README becomes visible to its trunk's staleness
  // check. But a directory whose OWN files keep mutating mid-run — e.g.
  // a pre-push file whose mtime gets bumped by hook re-installs while
  // this very sweep runs — stays needsAnalysis-positive forever and is
  // re-picked on every iteration, so the loop never drains.
  //
  // Because we process strictly bottom-up (children before trunks), no
  // directory ever LEGITIMATELY needs analysing twice in a single run. So
  // we analyse each dir at most once per invocation. A dir still flagged
  // stale after its turn is surfaced as "churn" (not silently dropped)
  // and then skipped.
  const analyzedThisRun = new Set();
  const churnReported = new Set();

  // Outer loop: each iteration handles ONE depth level. We re-walk the
  // tree each time so freshly-written child READMEs become visible to
  // trunk-staleness checks for the next iteration.
  for (;;) {
    const state = loadState(root);
    const actionable = [];
    for (const dir of walkDirs(root)) {
      // When --scope / --changed is in effect, only consider dirs in that scope.
      // Scope is pre-expanded to include ancestors, so trunk bubble-up
      // still fires for parents of the touched leaves.
      if (effectiveScope && !effectiveScope.has(dir)) continue;
      const reason = needsAnalysis(root, dir, state);
      if (!reason) continue;
      if (analyzedThisRun.has(dir)) {
        if (!churnReported.has(dir)) {
          churnReported.add(dir);
          onProgress?.({
            picked: relative(root, dir) || '.',
            skipped: 'churn',
            message:
              'still stale after analysis this run — files are changing ' +
              'under docgen (a live hook re-touching its own dir?); ' +
              'skipping to avoid a livelock',
          });
        }
        continue;
      }
      actionable.push({ dir, reason });
    }
    if (actionable.length === 0) break;

    // Restrict this batch to the deepest depth. Shallower dirs wait
    // for their children to finish on a future iteration.
    const depths = actionable.map((a) => a.dir.split('/').length);
    const maxDepth = Math.max(...depths);
    const sameDepth = actionable.filter(
      (a) => a.dir.split('/').length === maxDepth,
    );

    // Process the depth group in chunks of `parallel`. Within a chunk,
    // Promise.allSettled fans out; chunks themselves are serialised so
    // we never have more than `parallel` calls running. allSettled
    // (vs all) means one slot throwing doesn't discard the OTHER
    // concurrent results. The 'halt' detection below is the escape
    // hatch for truly-fatal errors (cwd deleted).
    for (let i = 0; i < sameDepth.length; i += parallel) {
      const chunk = sameDepth.slice(i, i + parallel);
      // Mark dispatched dirs as done-for-this-run BEFORE awaiting, so even
      // if their files mutate during analysis they are never re-queued.
      for (const b of chunk) analyzedThisRun.add(b.dir);
      onBatchStart?.({ depth: maxDepth, chunkSize: chunk.length });
      const settled = await Promise.allSettled(
        chunk.map((b) =>
          analyzeOne(root, { ...analyzeOpts, forceDir: b.dir }),
        ),
      );
      let halt = false;
      for (let j = 0; j < settled.length; j++) {
        const s = settled[j];
        if (s.status === 'fulfilled') {
          const r = s.value;
          if (r.skipped) skipped++;
          else if (r.picked) done++;
          onProgress?.(r);
        } else {
          skipped++;
          onProgress?.({
            picked: chunk[j].dir,
            skipped: 'error',
            message: s.reason?.message ?? String(s.reason),
          });
          if (s.reason?.halt || s.reason?.code === 'CWD_DELETED') halt = true;
        }
      }
      if (halt) {
        onProgress?.({
          picked: '<batch>',
          skipped: 'halt',
          message: 'cwd deleted (worktree cleanup); halting --until-done loop',
        });
        return { done, skipped, halted: true };
      }
    }
  }

  return { done, skipped };
}

// ─── status reporting ─────────────────────────────────────────────────────

export function computeStatus(root) {
  const state = loadState(root);
  const dirs = [];
  let skippedByFilter = 0;
  for (const dir of walkDirs(root)) {
    const rel = relative(root, dir) || '.';
    const entry = state.directories[rel];
    const reason = needsAnalysis(root, dir, state);
    // A dir that needsAnalysis declines (returns null) AND has no state
    // entry is one docgen will NEVER process — data-only, asset-dump
    // (>MAX_FILES_PER_DIR), no content. Excluding these from `total` keeps
    // the report honest on data-heavy repos (otherwise you'd see
    // "0/12000 documented" because most are skip-on-purpose research
    // dirs, not real backlog). Counted separately for visibility.
    if (!entry && !reason) {
      skippedByFilter += 1;
      continue;
    }
    dirs.push({
      dir: rel,
      analyzed: !!entry,
      lastAnalyzed: entry?.lastAnalyzed ?? null,
      needsReanalysis: reason,
    });
  }
  const total = dirs.length;
  // "Documented" counts auto-gen AUTO_DOCS.md that are fresh. A
  // hand-written README.md is invisible to docgen now, so there's no
  // "protected" bucket — every walked dir is a candidate for AUTO_DOCS.md.
  const documented = dirs.filter(
    (d) => d.analyzed && !d.needsReanalysis,
  ).length;
  const stale = dirs.filter((d) => d.analyzed && d.needsReanalysis).length;
  const uncovered = dirs.filter((d) => !d.analyzed).length;
  return { total, documented, stale, uncovered, skippedByFilter, dirs };
}

// ─── migrate: README.md → AUTO_DOCS.md ─────────────────────────────────────

/**
 * One-time migration from the OLD output filename (`README.md`) to the
 * new docgen-owned filename (`AUTO_DOCS.md`). For every directory under
 * `root` that has a docgen-MARKER-bearing `README.md` and NO existing
 * `AUTO_DOCS.md`, rename `README.md` → `AUTO_DOCS.md`.
 *
 * This is a PURE FILE MOVE — no `claude -p` calls, content preserved
 * byte-for-byte (so the embedded inputs-hash carries over and the
 * needsAnalysis skip-logic works immediately after migrating). Uses
 * `git mv` when in a git repo so history is preserved, else
 * `renameSync`.
 *
 * Hand-written README.md (no docgen marker) are left untouched.
 * Idempotent: a dir that already has AUTO_DOCS.md, or whose README.md is
 * hand-written, is skipped — re-running does nothing.
 *
 * Returns `{ migrated: string[], skipped: number }` where `migrated` is
 * the list of relative dir paths that were renamed and `skipped` counts
 * hand-written READMEs left alone.
 */
export function migrate(root, { dryRun = false } = {}) {
  const migrated = [];
  let skipped = 0;
  // Probe git once — if the repo isn't a git worktree, fall back to fs.
  let inGitRepo = false;
  try {
    execFileSync('git', ['rev-parse', '--is-inside-work-tree'], {
      cwd: root,
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    inGitRepo = true;
  } catch {
    inGitRepo = false;
  }

  for (const dir of walkDirs(root)) {
    const readmePath = join(dir, 'README.md');
    const docPath = join(dir, DOC_FILENAME);
    if (!existsSync(readmePath)) continue;
    // Already migrated (or a hand-written AUTO_DOCS.md exists) — leave it.
    if (existsSync(docPath)) continue;
    // Only docgen-authored READMEs move; hand-written ones stay put.
    if (!hasDocgenMarker(readmePath)) {
      skipped += 1;
      continue;
    }
    const rel = relative(root, dir) || '.';
    if (dryRun) {
      migrated.push(rel);
      continue;
    }
    if (inGitRepo) {
      try {
        execFileSync('git', ['mv', readmePath, docPath], {
          cwd: root,
          stdio: ['ignore', 'ignore', 'ignore'],
        });
      } catch {
        // git mv can fail if the file is untracked — fall back to a plain
        // rename so the migration still completes.
        renameSync(readmePath, docPath);
      }
    } else {
      renameSync(readmePath, docPath);
    }
    migrated.push(rel);
  }
  return { migrated, skipped };
}

// ─── CLI ──────────────────────────────────────────────────────────────────

function parseArgs(argv) {
  const out = { positional: [], flags: {} };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--until-done') out.flags.untilDone = true;
    else if (a === '--dry-run') out.flags.dryRun = true;
    else if (a === '--help' || a === '-h') out.flags.help = true;
    else if (a === '--dir') out.flags.dir = argv[++i];
    else if (a === '--model') out.flags.model = argv[++i];
    else if (a === '--timeout-ms') out.flags.timeoutMs = Number(argv[++i]);
    else if (a === '--parallel') out.flags.parallel = Math.max(1, Number(argv[++i]) || 1);
    else if (a === '--scope') out.flags.scope = argv[++i];
    else if (a === '--changed') {
      const raw = argv[++i] ?? '';
      out.flags.changed = raw.split(',').map((s) => s.trim()).filter(Boolean);
    }
    else out.positional.push(a);
  }
  return out;
}

function printHelp() {
  // Header comment at top of file is the spec.
  const here = fileURLToPath(new URL('.', import.meta.url));
  const self = join(here, 'docgen.mjs');
  const lines = readFileSync(self, 'utf8').split('\n');
  const start = lines.findIndex((l) => l.startsWith('/**'));
  const end = lines.findIndex((l, i) => i > start && l.includes('*/'));
  if (start < 0 || end < 0) {
    console.log('docgen — see header of docgen.mjs');
    return;
  }
  for (const l of lines.slice(start + 1, end)) {
    console.log(l.replace(/^ \* ?/, ''));
  }
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.flags.help) { printHelp(); return; }
  const sub = args.positional[0];
  const root = repoRoot();

  if (sub === 'status') {
    const s = computeStatus(root);
    const docTarget = s.total;
    const pct = docTarget === 0 ? 0 : ((s.documented / docTarget) * 100).toFixed(1);
    console.log(`docgen status — ${s.documented}/${docTarget} dirs documented (${pct}%)`);
    console.log(`  stale (needs re-analysis): ${s.stale}`);
    console.log(`  uncovered (never analyzed): ${s.uncovered}`);
    if (s.skippedByFilter > 0) {
      console.log(`  skipped (data/prose/asset-dump — no code to map): ${s.skippedByFilter}`);
    }
    const todo = s.dirs
      .filter((d) => !d.analyzed || d.needsReanalysis)
      .slice(0, 15);
    if (todo.length) {
      console.log('  next 15 todo:');
      for (const d of todo) {
        const reason = d.needsReanalysis ?? 'never-analyzed';
        console.log(`    - ${d.dir}  (${reason})`);
      }
    }
    // Auto-refresh is driven by the Claude Code PostToolUse hook
    // (tools/auto-docs-refresh.mjs, wired in .claude/settings.json) on PR
    // create/push — nothing to install per-clone, so no hook-state check here.
    return;
  }

  if (sub === 'migrate') {
    const res = migrate(root, { dryRun: args.flags.dryRun });
    for (const m of res.migrated) {
      console.log(`docgen migrate: ${args.flags.dryRun ? 'WOULD rename' : 'renamed'} ${m}/README.md → ${m}/${DOC_FILENAME}`);
    }
    console.log(
      `docgen migrate: ${args.flags.dryRun ? 'would migrate' : 'migrated'} ${res.migrated.length}, ` +
      `skipped ${res.skipped} hand-written.`,
    );
    return;
  }

  const here = dirname(fileURLToPath(import.meta.url));
  const promptText = loadPrompt(here);

  const runOpts = {
    promptText,
    forceDir: args.flags.dir,
    model: args.flags.model ?? DEFAULT_MODEL,
    timeoutMs: args.flags.timeoutMs ?? DEFAULT_TIMEOUT_MS,
    dryRun: args.flags.dryRun,
  };

  if (args.flags.untilDone) {
    // Sanity check before entering the loop — if our cwd is already
    // gone (parent automation deleted the worktree before we got
    // here), bail cleanly. Saves spawning a claude subprocess that
    // would only return "cwd deleted" itself.
    try { process.cwd(); } catch {
      console.log('docgen: cwd no longer exists — refusing to enter --until-done loop');
      process.exit(0);
    }
    // When --dir is set alongside --until-done, fall through to the
    // single-shot path. That's the explicit "force one target, no loop"
    // contract; --parallel doesn't apply to a single target.
    if (args.flags.dir) {
      const res = await analyzeOne(root, runOpts);
      if (!res.picked) {
        console.log('docgen: nothing to do.');
      } else if (res.skipped) {
        console.log(`docgen: SKIP ${res.picked} — ${res.message}`);
      } else {
        console.log(`docgen: ${res.dryRun ? 'DRY' : 'wrote'} ${res.picked} (${res.reason})`);
      }
      return;
    }
    const parallel = args.flags.parallel ?? 1;
    // --scope <comma-sep-paths>: restrict the walk to (paths + every
    // ancestor of each path) so a push-driven refresh only re-analyses
    // dirs containing files that just changed, while still letting
    // trunk bubble-up reach root through their ancestors.
    // --changed <comma-sep-relative-dirs>: same semantics as --scope but
    // takes relative dir paths (not file paths) — used by the pre-push
    // hook to pass the push diff's changed directories.
    let scopeSet = null;
    if (args.flags.scope) {
      const rawPaths = args.flags.scope
        .split(',')
        .map((s) => s.trim())
        .filter((s) => s.length > 0);
      // realpath the root so the ancestor walk's startsWith() check
      // works under macOS /tmp → /private/tmp symlink.
      let canonicalRoot;
      try { canonicalRoot = realpathSync(root); } catch { canonicalRoot = root; }
      scopeSet = expandScopeWithAncestors(canonicalRoot, rawPaths);
      console.log(`docgen: --scope restricts walk to ${scopeSet.size} dir(s) (paths + ancestors)`);
    }
    // --changed builds a scope from relative dir paths (the hook passes these).
    // If both --scope and --changed are given, --scope wins.
    let changedDirs = null;
    if (args.flags.changed && args.flags.changed.length > 0 && !scopeSet) {
      changedDirs = args.flags.changed;
      console.log(`docgen: --changed restricts walk to ${changedDirs.length} dir(s) + ancestors`);
    }
    let count = 0;
    const t0 = Date.now();
    const { done, skipped } = await analyzeAllParallel(root, {
      ...runOpts,
      parallel,
      scope: scopeSet,
      changed: changedDirs,
      onBatchStart: ({ depth, chunkSize }) => {
        console.log(`docgen: → batch at depth ${depth} (${chunkSize} in parallel)`);
      },
      onProgress: (res) => {
        if (res.skipped) {
          console.log(`docgen: SKIP ${res.picked} — ${res.message}`);
          return;
        }
        count++;
        const elapsed = ((Date.now() - t0) / 1000).toFixed(0);
        console.log(
          `docgen: [${count}] ${res.dryRun ? 'DRY' : 'wrote'} ${res.picked}` +
            ` (${res.reason}, v${res.finalVersion ?? '-'}, ${res.fileCount}f` +
            (res.childCount ? `+${res.childCount}c` : '') +
            `, ${elapsed}s elapsed)`,
        );
      },
    });
    const wall = ((Date.now() - t0) / 1000).toFixed(0);
    console.log(
      `docgen: done. ${done} dirs processed${skipped ? `, ${skipped} skipped` : ''}, ${wall}s wall-clock, parallel=${parallel}.`,
    );
    return;
  }

  const res = await analyzeOne(root, runOpts);
  if (!res.picked) {
    console.log('docgen: nothing to do — all dirs are documented and fresh.');
    return;
  }
  if (res.skipped) {
    console.log(`docgen: SKIP ${res.picked} — ${res.message}`);
    return;
  }
  if (res.dryRun) {
    console.log(`docgen: would analyze ${res.picked} (${res.reason}, ${res.fileCount} files)`);
  } else {
    console.log(`docgen: wrote ${res.readmePath} (${res.fileCount} files, ${res.bytes} bytes)`);
  }
}

// Run main() when invoked as a script. Tests import this file and only
// use the exported helpers. We canonicalize both sides via realpathSync
// because macOS resolves `/tmp/...` (argv) → `/private/tmp/...` (import
// URL), and a literal === would mis-classify the script as imported.
function invokedAsScript() {
  if (!process.argv[1]) return false;
  try {
    const a = realpathSync(resolve(process.argv[1]));
    const b = realpathSync(fileURLToPath(import.meta.url));
    return a === b;
  } catch {
    return false;
  }
}
if (invokedAsScript()) {
  main().catch((err) => {
    console.error(err.message);
    process.exit(1);
  });
}
