/**
 * Tests for the README-injection hook.
 *
 * Run with:  node --test tools/docgen/inject-readme-context.test.mjs
 *
 * Spawns the hook as a real subprocess (matching how Claude Code runs
 * it) with constructed stdin payloads and asserts on stdout + the
 * dedup state.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import {
  mkdtempSync,
  mkdirSync,
  writeFileSync,
  rmSync,
  existsSync,
  readFileSync,
} from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HOOK = join(
  dirname(fileURLToPath(import.meta.url)),
  'inject-readme-context.mjs',
);

/** Build a tmp git repo so the hook's `git rev-parse` succeeds. */
function freshGitRepo() {
  const root = mkdtempSync(join(tmpdir(), 'docgen-hook-'));
  execFileSync('git', ['init', '-q'], { cwd: root });
  // Suppress any user-level identity prompts.
  execFileSync('git', ['config', 'user.email', 'test@test'], { cwd: root });
  execFileSync('git', ['config', 'user.name', 'test'], { cwd: root });
  return root;
}

function file(root, rel, content) {
  const full = join(root, rel);
  mkdirSync(join(full, '..'), { recursive: true });
  writeFileSync(full, content);
  return full;
}

/** Invoke the hook with a payload; return { stdout, stderr, status }. */
function runHook(payload, { sessionId } = {}) {
  const full = sessionId
    ? { ...payload, session_id: sessionId }
    : payload;
  const r = spawnSync('node', [HOOK], {
    input: JSON.stringify(full),
    encoding: 'utf8',
    env: { ...process.env, DOCGEN_HOOK_TRACE: '0' },
  });
  return { stdout: r.stdout, stderr: r.stderr, status: r.status };
}

function clearDedup(sessionId) {
  const p = `/tmp/docgen-injected-${sessionId.replace(/[^A-Za-z0-9_-]/g, '_')}.json`;
  if (existsSync(p)) rmSync(p);
}

test('hook injects nearest AUTO_DOCS.md + ancestor AUTO_DOCS.md for a Read', () => {
  const root = freshGitRepo();
  try {
    file(root, 'AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nROOT README');
    file(root, 'pkg/AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nPKG README');
    file(root, 'pkg/sub/AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nSUB README');
    file(root, 'pkg/sub/file.ts', '// code');

    const sessionId = 'sess-' + Date.now();
    clearDedup(sessionId);
    const { stdout, status } = runHook(
      {
        tool_name: 'Read',
        tool_input: { file_path: join(root, 'pkg/sub/file.ts') },
      },
      { sessionId },
    );
    assert.equal(status, 0, 'hook must exit 0');
    assert.match(stdout, /SUB README/);
    assert.match(stdout, /PKG README/);
    assert.match(stdout, /ROOT README/);
    // Root-most first (broadest context at the top).
    const rootIdx = stdout.indexOf('ROOT README');
    const pkgIdx = stdout.indexOf('PKG README');
    const subIdx = stdout.indexOf('SUB README');
    assert.ok(rootIdx < pkgIdx, 'root must precede pkg');
    assert.ok(pkgIdx < subIdx, 'pkg must precede sub');
    clearDedup(sessionId);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('hook DEDUPS within a session — second call emits nothing', () => {
  const root = freshGitRepo();
  try {
    file(root, 'AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nROOT');
    file(root, 'a.ts', '// code');

    const sessionId = 'sess-dedup-' + Date.now();
    clearDedup(sessionId);

    const r1 = runHook(
      { tool_name: 'Read', tool_input: { file_path: join(root, 'a.ts') } },
      { sessionId },
    );
    assert.ok(r1.stdout.includes('ROOT'));

    const r2 = runHook(
      { tool_name: 'Read', tool_input: { file_path: join(root, 'a.ts') } },
      { sessionId },
    );
    assert.equal(r2.stdout, '', 'second call must dedup and emit nothing');
    clearDedup(sessionId);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('hook NOOPS when the target IS an AUTO_DOCS.md — no self-recursion', () => {
  const root = freshGitRepo();
  try {
    file(root, 'AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nROOT');
    file(root, 'pkg/AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nPKG');

    const sessionId = 'sess-readme-' + Date.now();
    clearDedup(sessionId);
    const r = runHook(
      {
        tool_name: 'Read',
        tool_input: { file_path: join(root, 'pkg/AUTO_DOCS.md') },
      },
      { sessionId },
    );
    assert.equal(r.stdout, '', 'reading an AUTO_DOCS.md must emit nothing');
    clearDedup(sessionId);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('hook emits nothing for tools without paths (e.g. TaskCreate)', () => {
  const root = freshGitRepo();
  try {
    file(root, 'AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nROOT');
    const r = runHook(
      { tool_name: 'TaskCreate', tool_input: { subject: 'do thing' } },
      { sessionId: 'sess-' + Date.now() },
    );
    assert.equal(r.stdout, '');
    assert.equal(r.status, 0);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('hook handles missing target gracefully — emits ancestor AUTO_DOCS.md for prospective Write', () => {
  const root = freshGitRepo();
  try {
    file(root, 'AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nROOT');
    file(root, 'pkg/AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nPKG');
    const sessionId = 'sess-write-' + Date.now();
    clearDedup(sessionId);
    const r = runHook(
      {
        tool_name: 'Write',
        tool_input: { file_path: join(root, 'pkg/new-file.ts') }, // doesn't exist yet
      },
      { sessionId },
    );
    assert.equal(r.status, 0);
    assert.ok(r.stdout.includes('PKG'), 'parent dir README must be injected even for new files');
    clearDedup(sessionId);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('hook injects AUTO_DOCS.md + CLAUDE.md but IGNORES a hand-written README.md', () => {
  const root = freshGitRepo();
  try {
    // A hand-written README.md sits in pkg/ — docgen owns AUTO_DOCS.md now,
    // so README.md must be invisible to the injection hook.
    file(root, 'pkg/README.md', '# My project\n\nHand-tuned, humans own this.');
    // The generated map lives at AUTO_DOCS.md.
    file(root, 'pkg/AUTO_DOCS.md', '<!-- auto-generated by docgen -->\n## Purpose\nGenerated map.');
    // A hand-written CLAUDE.md sidecar is still injected.
    file(root, 'pkg/CLAUDE.md', 'Rule: never do the bad thing.');
    file(root, 'pkg/code.ts', '// code');

    const sessionId = 'sess-mixed-' + Date.now();
    clearDedup(sessionId);
    const r = runHook(
      { tool_name: 'Read', tool_input: { file_path: join(root, 'pkg/code.ts') } },
      { sessionId },
    );
    assert.ok(r.stdout.includes('Generated map.'), 'generated AUTO_DOCS.md must be included');
    assert.ok(r.stdout.includes('never do the bad thing'), 'CLAUDE.md sidecar must be included');
    assert.ok(!r.stdout.includes('My project'),
      'hand-written README.md must NOT be injected — humans own it');
    clearDedup(sessionId);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('hook records the agents EXPLICIT AUTO_DOCS.md reads — skips them on later injection', () => {
  const root = freshGitRepo();
  try {
    file(root, 'AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nROOT');
    file(root, 'pkg/AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nPKG');
    file(root, 'pkg/sub/AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nSUB');
    file(root, 'pkg/sub/file.ts', '// code');

    const sessionId = 'sess-explicit-' + Date.now();
    clearDedup(sessionId);

    // 1) Agent EXPLICITLY Reads pkg/AUTO_DOCS.md — hook NOOPs (no
    //    self-injection) but should record it as "already in context".
    const r1 = runHook(
      { tool_name: 'Read', tool_input: { file_path: join(root, 'pkg/AUTO_DOCS.md') } },
      { sessionId },
    );
    assert.equal(r1.stdout, '', 'reading an AUTO_DOCS.md itself must NOT emit injection');

    // 2) Agent Reads a sibling source file. Ancestor walk would include
    //    root, pkg, pkg/sub. But pkg/AUTO_DOCS.md was already Read, so it
    //    must be skipped while the others still appear.
    const r2 = runHook(
      { tool_name: 'Read', tool_input: { file_path: join(root, 'pkg/sub/file.ts') } },
      { sessionId },
    );
    assert.ok(r2.stdout.includes('ROOT'), 'root AUTO_DOCS.md must still appear');
    assert.ok(r2.stdout.includes('SUB'), 'sub AUTO_DOCS.md must still appear');
    assert.ok(!r2.stdout.includes('PKG'),
      `pkg AUTO_DOCS.md must NOT reappear — agent already read it. Got: ${r2.stdout.slice(0, 300)}`);

    clearDedup(sessionId);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('hook never throws on garbage stdin — silent exit 0', () => {
  const r = spawnSync('node', [HOOK], {
    input: 'not valid json {',
    encoding: 'utf8',
    env: { ...process.env, DOCGEN_HOOK_TRACE: '0' },
  });
  assert.equal(r.status, 0, 'hook must NEVER exit non-zero (would block tool call)');
  assert.equal(r.stdout, '');
});

test('hook never throws on empty stdin — silent exit 0', () => {
  const r = spawnSync('node', [HOOK], {
    input: '',
    encoding: 'utf8',
    env: { ...process.env, DOCGEN_HOOK_TRACE: '0' },
  });
  assert.equal(r.status, 0);
  assert.equal(r.stdout, '');
});

// ─── telemetry parity (end-to-end via subprocess) ────────────────────────
//
// Verifies the hook actually writes to ~/.claude-telemetry/. Each test
// redirects via CLAUDE_TELEMETRY_ROOT so it doesn't pollute the
// operator's real log dir. Catches regressions like the long-standing
// `tool` ReferenceError that silently swallowed every docgen telemetry
// fire from #12 until this PR.

function runHookWithTelemetry(payload, { sessionId, telemetryRoot }) {
  const full = sessionId ? { ...payload, session_id: sessionId } : payload;
  return spawnSync('node', [HOOK], {
    input: JSON.stringify(full),
    encoding: 'utf8',
    env: {
      ...process.env,
      DOCGEN_HOOK_TRACE: '0',
      CLAUDE_TELEMETRY_ROOT: telemetryRoot,
    },
  });
}

function readTelemetry(telemetryRoot, sessionId) {
  const path = join(telemetryRoot, 'sessions', `${sessionId}.jsonl`);
  if (!existsSync(path)) return [];
  return readFileSync(path, 'utf8')
    .trim()
    .split('\n')
    .filter(Boolean)
    .map((l) => JSON.parse(l));
}

test('telemetry: writes one `injected` row when README(s) get emitted', () => {
  const root = freshGitRepo();
  const telemetryRoot = mkdtempSync(join(tmpdir(), 'docgen-telem-'));
  const sessionId = 'telem-inject-test';
  try {
    file(root, 'AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nROOT MAP');
    file(root, 'src/AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nSRC MAP');
    file(root, 'src/app.js', 'console.log("x")');
    clearDedup(sessionId);

    const r = runHookWithTelemetry(
      { tool_name: 'Read', tool_input: { file_path: join(root, 'src/app.js') } },
      { sessionId, telemetryRoot },
    );
    assert.equal(r.status, 0);

    const rows = readTelemetry(telemetryRoot, sessionId);
    assert.equal(rows.length, 1, 'should land exactly one telemetry row');
    assert.equal(rows[0].hook, 'docgen-inject-readme-context');
    assert.equal(rows[0].event, 'injected');
    assert.equal(rows[0].tool, 'Read');
    assert.ok(rows[0].bytes_emitted > 0, 'bytes_emitted must reflect real payload size');
    assert.ok(
      Array.isArray(rows[0].files_injected) && rows[0].files_injected.length >= 1,
      'files_injected must list the READMEs that were emitted',
    );

    clearDedup(sessionId);
  } finally {
    rmSync(root, { recursive: true, force: true });
    rmSync(telemetryRoot, { recursive: true, force: true });
  }
});

test('telemetry: writes a `deduped` row on the second call in the same session', () => {
  const root = freshGitRepo();
  const telemetryRoot = mkdtempSync(join(tmpdir(), 'docgen-telem-'));
  const sessionId = 'telem-dedup-test';
  try {
    file(root, 'AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nROOT');
    file(root, 'src/AUTO_DOCS.md', '<!-- auto-generated by docgen -->\nSRC');
    file(root, 'src/a.js', 'a');
    clearDedup(sessionId);

    // First fire — injects.
    runHookWithTelemetry(
      { tool_name: 'Read', tool_input: { file_path: join(root, 'src/a.js') } },
      { sessionId, telemetryRoot },
    );
    // Second fire on a sibling file — every README in the chain is
    // already in the dedup set, so collected becomes empty → deduped.
    file(root, 'src/b.js', 'b');
    runHookWithTelemetry(
      { tool_name: 'Read', tool_input: { file_path: join(root, 'src/b.js') } },
      { sessionId, telemetryRoot },
    );

    const rows = readTelemetry(telemetryRoot, sessionId);
    assert.equal(rows.length, 2, 'first fire = injected, second = deduped');
    assert.equal(rows[0].event, 'injected');
    assert.equal(rows[1].event, 'deduped');
    assert.equal(rows[1].bytes_emitted, 0);
    assert.equal(rows[1].tool, 'Read');

    clearDedup(sessionId);
  } finally {
    rmSync(root, { recursive: true, force: true });
    rmSync(telemetryRoot, { recursive: true, force: true });
  }
});

test('telemetry: writes NOTHING for out-of-repo paths (no fake-deduped noise)', () => {
  const telemetryRoot = mkdtempSync(join(tmpdir(), 'docgen-telem-'));
  const sessionId = 'telem-out-of-repo-test';
  try {
    // Point at a file outside any git repo: /tmp itself isn't a git
    // repo, so repoRoot() returns null and the hook bails before any
    // injection. The previous `deduped` event would have been emitted
    // — now it must NOT be.
    const outsideFile = join(telemetryRoot, 'not-in-repo.txt');
    writeFileSync(outsideFile, 'hi');

    runHookWithTelemetry(
      { tool_name: 'Read', tool_input: { file_path: outsideFile } },
      { sessionId, telemetryRoot },
    );

    const rows = readTelemetry(telemetryRoot, sessionId);
    assert.equal(
      rows.length,
      0,
      'out-of-repo fires must exit silently — no telemetry row',
    );
  } finally {
    rmSync(telemetryRoot, { recursive: true, force: true });
  }
});

test('telemetry: writes NOTHING for non-path tools like Bash/TaskCreate', () => {
  const telemetryRoot = mkdtempSync(join(tmpdir(), 'docgen-telem-'));
  const sessionId = 'telem-no-path-test';
  try {
    runHookWithTelemetry(
      { tool_name: 'Bash', tool_input: { command: 'ls' } },
      { sessionId, telemetryRoot },
    );

    const rows = readTelemetry(telemetryRoot, sessionId);
    assert.equal(rows.length, 0, 'Bash and other non-path tools should not log');
  } finally {
    rmSync(telemetryRoot, { recursive: true, force: true });
  }
});
