#!/usr/bin/env node
/**
 * validate-all.mjs — batch-validate docgen-generated AUTO_DOCS.md and stamp
 * each one's score into its docgen version header. Mirrors systems-registry's
 * validate-all.mjs.
 *
 * Usage:
 *   node tools/claude-code-auto-documentation/validate-all.mjs [--scope a,b,c]
 *     [--changed-since <sha>] [--concurrency N] [--limit N]
 *
 *   --scope          comma-separated list of dirs to validate (relative to repo)
 *   --changed-since  validate only READMEs whose dir changed since this sha
 *   --concurrency    parallel judge calls (default 3)
 *   --limit          stop after N (useful for cost-bounded smoke runs)
 */
import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, dirname, relative } from 'node:path';
import { validateReadme } from './validate-readme.mjs';

function repoRoot() {
  try { return execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim(); }
  catch { return process.cwd(); }
}

const args = process.argv.slice(2);
const cIdx = args.indexOf('--concurrency');
const concurrency = cIdx !== -1 ? Number(args[cIdx + 1]) : 3;
const limIdx = args.indexOf('--limit');
const limit = limIdx !== -1 ? Number(args[limIdx + 1]) : 0;
const scIdx = args.indexOf('--scope');
const scope = scIdx !== -1 ? args[scIdx + 1].split(',').map(s => s.trim()) : null;
const csIdx = args.indexOf('--changed-since');
const changedSince = csIdx !== -1 ? args[csIdx + 1] : null;

const root = repoRoot();
const DOCGEN_MARKER = 'auto-generated by docgen';
const DOC_FILENAME = 'AUTO_DOCS.md';

// Find all docgen-generated AUTO_DOCS.md.
function* walk(dir) {
  let entries;
  try { entries = execFileSync('git', ['ls-files', dir], { cwd: root, encoding: 'utf8' }).split('\n').filter(Boolean); }
  catch { return; }
  for (const e of entries) yield e;
}

// Tighter than substring match: the marker MUST be inside the first
// HTML comment (docgen always writes it as the very first line). This
// avoids false-positives where the marker is quoted in hand-written prose
// (and AUTO_DOCS.md is docgen-owned anyway, so collisions are unlikely).
function readmeIsDocgen(absPath) {
  try {
    const head = readFileSync(absPath, 'utf8').slice(0, 256);
    const firstComment = head.match(/^<!--([\s\S]*?)-->/);
    return !!firstComment && firstComment[1].includes(DOCGEN_MARKER);
  } catch { return false; }
}

let candidates;
if (changedSince) {
  const out = execFileSync('git', ['diff', '--name-only', `${changedSince}..HEAD`], { cwd: root, encoding: 'utf8' });
  candidates = out.split('\n').filter(p => p.endsWith(`/${DOC_FILENAME}`) || p === DOC_FILENAME);
} else if (scope) {
  candidates = scope.map(d => join(d, DOC_FILENAME));
} else {
  // All tracked AUTO_DOCS.md.
  const out = execFileSync('git', ['ls-files', `*/${DOC_FILENAME}`, DOC_FILENAME], { cwd: root, encoding: 'utf8' });
  candidates = out.split('\n').filter(Boolean);
}

const targets = [];
for (const rel of candidates) {
  const abs = join(root, rel);
  if (!existsSync(abs)) continue;
  if (!readmeIsDocgen(abs)) continue;
  targets.push({ rel, abs, dir: dirname(abs), dirLabel: dirname(rel) });
}

const effective = limit > 0 ? targets.slice(0, limit) : targets;
process.stdout.write(`validating ${effective.length} READMEs (concurrency=${concurrency}${limit ? `, limit=${limit}` : ''})\n\n`);

/** Stamp `quality_score: X.Y (verdict)` into the docgen version comment header.
 *  Idempotent: replaces an existing stamp or appends one inline. */
function stampScore(absPath, score, verdict) {
  const text = readFileSync(absPath, 'utf8');
  const lines = text.split('\n');
  let changed = false;
  for (let i = 0; i < Math.min(lines.length, 6); i++) {
    if (lines[i].includes('docgen:version=')) {
      // Strip prior stamp, add fresh one.
      const cleaned = lines[i].replace(/\s+quality=[\d.]+(\s+verdict=\w+)?/, '');
      lines[i] = cleaned.replace(/-->\s*$/, `quality=${score} verdict=${verdict} -->`);
      changed = true;
      break;
    }
  }
  if (!changed) {
    // No version header — prepend a quality-only header above first line.
    lines.unshift(`<!-- docgen:quality=${score} verdict=${verdict} -->`);
  }
  writeFileSync(absPath, lines.join('\n'));
}

const results = [];
let next = 0;
async function runOne(t) {
  const t0 = Date.now();
  try {
    const r = await validateReadme(t.dir, { root });
    const score = r.scores.overall;
    stampScore(t.abs, score, r.verdict);
    const ms = Date.now() - t0;
    results.push({ rel: t.rel, score, verdict: r.verdict, issues: r.issues?.length || 0, ms });
    process.stdout.write(`  ${t.dirLabel}: ${score}/10 (${r.verdict})  issues=${r.issues?.length || 0}  ${(ms/1000).toFixed(1)}s\n`);
  } catch (err) {
    results.push({ rel: t.rel, score: null, error: String(err.message || err) });
    process.stdout.write(`  ${t.dirLabel}: ERROR — ${err.message || err}\n`);
  }
}

async function loop() {
  while (next < effective.length) {
    const t = effective[next++];
    await runOne(t);
  }
}

const tasks = [];
for (let i = 0; i < concurrency; i++) tasks.push(loop());
const start = Date.now();
await Promise.all(tasks);
const elapsed = (Date.now() - start) / 1000;

results.sort((a, b) => (b.score ?? -1) - (a.score ?? -1));
process.stdout.write(`\n=== summary (${elapsed.toFixed(1)}s wall) ===\n`);
const passed = results.filter(r => r.score >= 7).length;
const below = results.filter(r => r.score !== null && r.score < 7).length;
const errored = results.filter(r => r.score === null).length;
process.stdout.write(`pass(>=7): ${passed}   below: ${below}   errored: ${errored}\n\n`);
for (const r of results.slice(0, 50)) {
  if (r.score === null) {
    process.stdout.write(`  ✗ ${r.rel}: ERROR ${r.error}\n`);
  } else {
    const tag = r.score >= 7 ? '✓' : '✗';
    process.stdout.write(`  ${tag} ${r.rel}: ${r.score}/10\n`);
  }
}

process.exit(errored > 0 ? 1 : 0);
