/**
 * Hermetic tests for docgen's README validator. Injected runners (canned
 * JSON) — nothing spawns claude/codex/gemini.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  buildReadmeValidatePrompt, parseReadmeValidation, judgeCommand,
  selectDirFiles, validateReadme, withRetry,
} from './validate-readme.mjs';

function fixtureDir(setup) {
  const root = mkdtempSync(join(tmpdir(), 'dg-val-'));
  setup(root);
  return root;
}
const cleanup = r => { try { rmSync(r, { recursive: true, force: true }); } catch { /* */ } };

describe('selectDirFiles', () => {
  it('lists source files, skips AUTO_DOCS.md / README.md / dotfiles / binaries', () => {
    const d = fixtureDir(r => {
      writeFileSync(join(r, 'a.ts'), 'export const a = 1;');
      writeFileSync(join(r, 'b.mjs'), 'export const b = 2;');
      writeFileSync(join(r, 'AUTO_DOCS.md'), '<!-- auto-generated by docgen -->');
      writeFileSync(join(r, 'README.md'), '# readme');
      writeFileSync(join(r, '.hidden'), 'x');
      writeFileSync(join(r, 'logo.png'), 'binary');
    });
    try {
      const names = selectDirFiles(d).map(f => f.name);
      assert.deepEqual(names, ['a.ts', 'b.mjs']);   // sorted, filtered
    } finally { cleanup(d); }
  });
});

describe('buildReadmeValidatePrompt', () => {
  it('embeds the README, the files, the rubric, and the hard cap', () => {
    const p = buildReadmeValidatePrompt({
      readme: '## Purpose\nDoes X.\n## Map\n- thing → a.ts · doThing',
      files: [{ name: 'a.ts', content: 'export function doThing(){}' }],
      dirLabel: 'apps/x',
    });
    assert.match(p, /DO NOT TRUST THE README/);
    assert.match(p, /apps\/x/);
    assert.match(p, /doThing\(\)/);          // file embedded
    assert.match(p, /Map.*file · Symbol|file · Symbol/s);
    assert.match(p, /HARD CAP/);
    assert.match(p, /STRICT JSON ONLY/);
  });
});

describe('parseReadmeValidation', () => {
  it('computes weighted overall to one decimal (no defects)', () => {
    // .45*10 + .35*8 + .20*9 = 4.5+2.8+1.8 = 9.1
    const r = parseReadmeValidation('{"scores":{"correctness":10,"completeness":8,"sizing":9},"verdict":"ship","issues":[],"missing":[],"suggestions":[]}');
    assert.equal(r.scores.overall, 9.1);
    assert.equal(r.verdict, 'ship');
  });

  it('HARD CAP: a hallucinated symbol (issue) forces overall ≤ 7', () => {
    const r = parseReadmeValidation('{"scores":{"correctness":10,"completeness":10,"sizing":10,"overall":10},"verdict":"ship","issues":["Map cites doThing — not in a.ts"],"missing":[],"suggestions":[]}');
    assert.equal(r.scores.overall, 7);
  });

  it('HARD CAP: an omitted load-bearing file (missing) also caps at 7', () => {
    const r = parseReadmeValidation('{"scores":{"correctness":10,"completeness":10,"sizing":10},"verdict":"ship","issues":[],"missing":["b.mjs undocumented"],"suggestions":[]}');
    assert.equal(r.scores.overall, 7);
  });

  it('tolerates ```json fences + prose', () => {
    const r = parseReadmeValidation('Review:\n```json\n{"scores":{"correctness":6,"completeness":6,"sizing":7},"verdict":"revise","issues":["x"],"missing":[],"suggestions":["y"]}\n```');
    assert.equal(r.scores.correctness, 6);
    assert.deepEqual(r.issues, ['x']);
  });

  it('throws on no-JSON response', () => {
    assert.throws(() => parseReadmeValidation('could not comply'), /no JSON|parse/);
  });
});

describe('judgeCommand', () => {
  it('defaults to claude -p', () => {
    delete process.env.DOCGEN_JUDGE_CMD;
    const c = judgeCommand();
    assert.equal(c.cmd, 'claude'); assert.ok(c.args.includes('-p')); assert.equal(c.source, 'default');
  });
  it('honors DOCGEN_JUDGE_CMD (codex/gemini)', () => {
    process.env.DOCGEN_JUDGE_CMD = 'gemini -p';
    const c = judgeCommand();
    assert.equal(c.cmd, 'gemini'); assert.deepEqual(c.args, ['-p']); assert.equal(c.source, 'DOCGEN_JUDGE_CMD');
    delete process.env.DOCGEN_JUDGE_CMD;
  });
});

describe('validateReadme', () => {
  it('dry-run returns prompt + command, runs nothing', async () => {
    const d = fixtureDir(r => {
      writeFileSync(join(r, 'a.ts'), 'export const a = 1;');
      writeFileSync(join(r, 'AUTO_DOCS.md'), '## Purpose\nx\n## Map\n- a → a.ts · a');
    });
    try {
      const r = await validateReadme(d, { dryRun: true });
      assert.equal(r.dryRun, true);
      assert.match(r.prompt, /Score each 0-10/);
      assert.ok(r.command.display.length > 0);
    } finally { cleanup(d); }
  });

  it('runs injected runner → parsed result; throws if no AUTO_DOCS.md', async () => {
    const d = fixtureDir(r => {
      writeFileSync(join(r, 'a.ts'), 'export const a = 1;');
      writeFileSync(join(r, 'AUTO_DOCS.md'), '## Purpose\nx');
    });
    try {
      const runner = async () => '{"scores":{"correctness":9,"completeness":9,"sizing":9},"verdict":"ship","issues":[],"missing":[],"suggestions":[]}';
      const res = await validateReadme(d, { runner });
      assert.equal(res.scores.overall, 9);
      // no-AUTO_DOCS.md dir throws (a bare README.md does NOT satisfy it)
      const empty = fixtureDir(r => { writeFileSync(join(r, 'README.md'), '# hand-written'); });
      await assert.rejects(validateReadme(empty, { runner }), /no AUTO_DOCS\.md/);
      cleanup(empty);
    } finally { cleanup(d); }
  });
});

describe('withRetry', () => {
  it('retries then succeeds', async () => {
    let n = 0;
    const r = await withRetry(async () => { n++; if (n < 2) throw new Error('flake'); return 'ok'; }, { retries: 2, baseDelayMs: 1 });
    assert.equal(r, 'ok'); assert.equal(n, 2);
  });
});
