#!/usr/bin/env node
/**
 * systems-registry — composite cross-system README generator.
 *
 * Reads `docs/systems/_hypothesis.md` (the LLM-authored systems map with
 * its `consumes:` relationships), the per-system manifests (for current
 * summaries + categories), and writes a fresh `docs/systems/README.md`
 * with an auto-derived Mermaid composite diagram + a categorized table.
 *
 * Before this module the composite README was hand-curated and froze on
 * its initial commit — every regenerated system page after PR #1397 still
 * pointed at stale node names. This closes that gap: the composite is
 * derived from the same hypothesis that drives Pass 2, so it can't drift
 * out of sync with the system set.
 *
 * No LLM call. Pure data assembly from on-disk artifacts.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { repoMeta } from './repo-meta.mjs';

const PROGRAM = 'systems-registry';
const HEADER = `<!-- auto-generated by ${PROGRAM} composite — refresh with \`tools/systems-registry/cli.mjs build\` -->`;

/**
 * Parse `_hypothesis.md` into {name, summary, consumes[]} entries.
 * Tolerant of YAML formatting; gives up on commentary that ended up inside
 * a consumes: list (filtered out by name-validity at composite-build time).
 */
export function parseHypothesis(text) {
  const m = text.match(/systems:\n([\s\S]*?)(?:\n##\s|\n---\s|$)/);
  if (!m) return [];
  const out = [];
  const chunks = m[1].split(/^\s*-\s*name:\s*/m);
  for (let i = 1; i < chunks.length; i++) {
    const chunk = chunks[i];
    const firstNl = chunk.indexOf('\n');
    const name = chunk.slice(0, firstNl === -1 ? chunk.length : firstNl).trim().replace(/^["']|["']$/g, '');
    const rest = firstNl === -1 ? '' : chunk.slice(firstNl + 1);
    const entry = { name, summary: '', consumes: [], kind: null, closes_loop_via: '' };
    let inConsumes = false;
    let inSummary = false;
    for (const raw of rest.split('\n')) {
      // YAML block scalar continuation for `summary: >-`
      if (/^\s*summary:\s*>/.test(raw)) { inSummary = true; inConsumes = false; continue; }
      if (inSummary && /^\s+\S/.test(raw) && !/^\s*[a-z_][\w-]*:\s*($|\S)/.test(raw)) {
        entry.summary += raw.trim() + ' '; continue;
      }
      if (/^\s*summary:\s*/.test(raw)) { entry.summary = raw.replace(/^\s*summary:\s*/, '').trim().replace(/^["']|["']$/g, ''); inConsumes = false; inSummary = false; continue; }
      // kind + closes_loop_via — both bounded to top-level (0-4 spaces) so
      // an indented sub-key from a future nested field doesn't overwrite them.
      const kindM = raw.match(/^\s{0,4}kind:\s*(.+)$/);
      if (kindM) { entry.kind = kindM[1].trim().replace(/^["']|["']$/g, ''); inConsumes = false; inSummary = false; continue; }
      const clvM = raw.match(/^\s{0,4}closes_loop_via:\s*(.+)$/);
      if (clvM) { entry.closes_loop_via = clvM[1].trim().replace(/^["']|["']$/g, ''); inConsumes = false; inSummary = false; continue; }
      if (/^\s*consumes:/.test(raw)) {
        inConsumes = true; inSummary = false;
        // Inline-array form: `consumes: [a, b]` — extract and stay out of block mode.
        const inline = raw.match(/^\s*consumes:\s*\[([^\]]*)\]/);
        if (inline) {
          for (const v of inline[1].split(',').map(s => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean)) {
            entry.consumes.push(v);
          }
          inConsumes = false;
        }
        continue;
      }
      if (/^\s*[a-z_]+:/.test(raw)) { inConsumes = false; inSummary = false; }
      if (inConsumes && /^\s*-\s/.test(raw)) {
        const v = raw.replace(/^\s*-\s*/, '').trim().replace(/^["']|["']$/g, '');
        entry.consumes.push(v);
      }
    }
    entry.summary = entry.summary.trim();
    out.push(entry);
  }
  return out;
}

/** A "consumes" entry counts only if it names a real sibling system on disk. */
function filterValidConsumes(systems) {
  const names = new Set(systems.map(s => s.name));
  for (const s of systems) {
    s.consumes = (s.consumes || []).filter(c => names.has(c));
  }
  return systems;
}

/** Mermaid-safe id: a-z, 0-9, underscore. */
function nodeId(name) {
  return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

// Subgraph mapping by `kind`. The overview groups systems into 2-4 visible
// phases so the eye can scan them as a story (Bootstrap → Producers → Hooks
// → Gates), not as a flat 6-box DAG. Order matters — `SUBGRAPH_ORDER` is the
// vertical reading order in the rendered diagram.
const KIND_TO_SUBGRAPH = {
  installer:     'Bootstrap',
  pipeline:      'Producers',
  'loop-driver': 'Producers',
  'data-product':'Producers',
  hook:          'Hooks',
  gate:          'Gates',
};
const SUBGRAPH_ORDER = ['Bootstrap', 'Producers', 'Hooks', 'Gates', 'Other'];

const KIND_STYLES = {
  pipeline:      'fill:#1f3a5f,stroke:#58a6ff,color:#c9d1d9',
  hook:          'fill:#3f2a5f,stroke:#bc8cff,color:#c9d1d9',
  installer:     'fill:#2f4a2a,stroke:#7ee787,color:#c9d1d9',
  gate:          'fill:#5a3a1f,stroke:#ffa657,color:#c9d1d9',
  'loop-driver': 'fill:#1f4a4a,stroke:#39c5cf,color:#c9d1d9',
  'data-product':'fill:#5f1f3a,stroke:#ff7b9c,color:#c9d1d9',
  unknown:       'fill:#21262d,stroke:#7d8590,color:#c9d1d9',
};

// Synthetic anchor nodes — the overview makes the LOOP visible by routing
// every system's closes-loop arrow to one of these endpoints. The targets
// don't exist as system pages on disk; they're the conceptual edges the
// real systems close into.
const SYNTHETIC_ANCHORS = {
  next_llm_turn: { id: 'claude_turn',  label: 'Claude<br/>(next LLM turn)', shape: 'stadium' },
  host_repo:     { id: 'host_repo',    label: 'Host repo<br/>(files on disk)', shape: 'stadium' },
  db_table:      { id: 'db_target',    label: 'Database',  shape: 'cylinder' },
  chain_tx:      { id: 'chain_target', label: 'On-chain',  shape: 'hexagon' },
  tg_message:    { id: 'tg_target',    label: 'Telegram',  shape: 'stadium' },
  dashboard:     { id: 'dashboard_target', label: 'Dashboard', shape: 'stadium' },
};

function kindKey(kind) {
  const k = (kind || 'unknown').toLowerCase();
  return KIND_STYLES[k] ? k : 'unknown';
}
function kindClass(kind) {
  return `kind_${kindKey(kind).replace(/-/g, '_')}`;
}

/**
 * Extract the closes-loop token from `closes_loop_via`. The Pass 1 prompt
 * asks for one of the known tokens as the FIRST word — e.g.
 * `next_llm_turn — via PreToolUse hook`. Returns the matching anchor key
 * or null when the text doesn't start with a known token.
 */
function closesLoopToken(s) {
  const text = (s.closes_loop_via || '').toLowerCase();
  if (!text) return null;
  for (const key of Object.keys(SYNTHETIC_ANCHORS)) {
    if (text.startsWith(key)) return key;
  }
  if (text.startsWith('none')) return 'none';
  return null;
}

function shapeFor(label, shape) {
  if (shape === 'stadium')  return `(["${label}"])`;
  if (shape === 'cylinder') return `[("${label}")]`;
  if (shape === 'hexagon')  return `{{"${label}"}}`;
  return `["${label}"]`;
}

/**
 * Render the cross-system Mermaid as a STORY, not a one-color DAG:
 *  - Nodes are grouped into subgraphs by `kind` (Bootstrap / Producers /
 *    Hooks / Gates) so the eye reads phases, not flat boxes.
 *  - Synthetic anchor nodes (Claude / Host repo / Database / etc.) make
 *    the loop visible — every system's `closes_loop_via` token routes its
 *    feedback arrow to one of these endpoints.
 *  - `consumes:` edges remain as solid grey arrows between real systems.
 *  - The closes-loop arrows are thick blue and labeled with the
 *    closes_loop_via prose (the part after the token).
 *  - Nodes are colored by `kind`.
 */
export function renderCompositeMermaid(systems) {
  const lines = ['```mermaid', 'flowchart TB'];

  // Bucket systems by subgraph.
  const buckets = new Map(SUBGRAPH_ORDER.map(n => [n, []]));
  for (const s of systems) {
    const bucket = KIND_TO_SUBGRAPH[kindKey(s.kind)] || 'Other';
    buckets.get(bucket).push(s);
  }

  // Emit subgraphs in fixed order. Skip empties so a repo with only
  // pipelines doesn't render an empty `Bootstrap` chrome.
  for (const name of SUBGRAPH_ORDER) {
    const items = buckets.get(name);
    if (!items || items.length === 0) continue;
    lines.push(`  subgraph ${name.toLowerCase()}_grp ["${name}"]`);
    for (const s of items) {
      lines.push(`    ${nodeId(s.name)}["${s.name}"]:::${kindClass(s.kind)}`);
    }
    lines.push('  end');
  }

  // Synthetic anchor nodes — emit only those actually referenced by some
  // system's closes_loop_via token, so we don't clutter an overview where
  // nothing closes via DB / chain / dashboard etc.
  const referencedAnchors = new Set();
  for (const s of systems) {
    const tok = closesLoopToken(s);
    if (tok && tok !== 'none' && SYNTHETIC_ANCHORS[tok]) referencedAnchors.add(tok);
  }
  if (referencedAnchors.size > 0) {
    lines.push(`  subgraph endpoints_grp ["Closes-loop into"]`);
    for (const tok of referencedAnchors) {
      const a = SYNTHETIC_ANCHORS[tok];
      lines.push(`    ${a.id}${shapeFor(a.label, a.shape)}:::anchor`);
    }
    lines.push('  end');
  }

  // Edges. consumes = solid grey; closes-loop = thick blue with the prose
  // label after the token. Filtered against real system names for consumes.
  const realNames = new Set(systems.map(s => s.name));
  for (const s of systems) {
    for (const c of s.consumes || []) {
      if (realNames.has(c)) lines.push(`  ${nodeId(s.name)} --> ${nodeId(c)}`);
    }
    const tok = closesLoopToken(s);
    if (tok && tok !== 'none' && SYNTHETIC_ANCHORS[tok]) {
      const raw = (s.closes_loop_via || '').slice(tok.length).replace(/^[\s—\-:,]+/, '');
      const tail = truncateLabel(raw, 48);
      const labelStr = tail ? `|${escapeLabel(tail)}|` : '';
      lines.push(`  ${nodeId(s.name)} ==>${labelStr} ${SYNTHETIC_ANCHORS[tok].id}`);
    }
  }

  // Class defs + anchor styling.
  for (const [k, style] of Object.entries(KIND_STYLES)) {
    lines.push(`  classDef ${kindClass(k)} ${style}`);
  }
  lines.push('  classDef anchor fill:#0d2030,stroke:#58a6ff,color:#c9d1d9,stroke-dasharray: 4 2');

  // Clickable nodes. Synthetic anchors don't have system pages — skip them.
  for (const s of systems) {
    lines.push(`  click ${nodeId(s.name)} "#${s.name}" _self`);
  }

  lines.push('```');
  return lines.join('\n');
}

// Escape characters that break Mermaid edge labels. Pipes terminate the
// label; quotes get mangled. Keep it ASCII-safe.
function escapeLabel(s) {
  return String(s).replace(/[|"`]/g, '');
}

// Truncate an edge label at a WORD boundary near `max` chars, then strip
// dangling punctuation + add an ellipsis. A naive `.slice(0, max)` cut
// mid-word and left trailing junk ("...injected into the model'",
// "...back onto ;"). This keeps labels readable.
function truncateLabel(s, max) {
  const str = String(s).trim();
  if (str.length <= max) return str.replace(/[\s;:,.\-—'"]+$/, '');
  const cut = str.slice(0, max);
  // Back up to the last space so we don't end mid-word; fall back to a hard
  // cut if there's no space in range (one very long token).
  const lastSpace = cut.lastIndexOf(' ');
  const base = lastSpace > max * 0.5 ? cut.slice(0, lastSpace) : cut;
  return base.replace(/[\s;:,.\-—'"]+$/, '') + '…';
}

/** Read per-system manifests for the table summaries. */
function readManifestSummaries(repoRoot) {
  const dir = join(repoRoot, 'docs/systems');
  const out = {};
  if (!existsSync(dir)) return out;
  for (const f of readdirSync(dir)) {
    if (!f.endsWith('.md') || f === 'README.md' || f.startsWith('_')) continue;
    const text = readFileSync(join(dir, f), 'utf8');
    const name = f.replace(/\.md$/, '');
    // Pull the summary out of the front-matter — handles `summary: >-`
    // YAML block-scalar form and inline form.
    const m = text.match(/^summary:\s*>-?\s*\n((?:\s+\S.*\n)+)/m)
           || text.match(/^summary:\s*(.+)$/m);
    if (m) {
      out[name] = (m[1] || '').replace(/\n\s+/g, ' ').trim().slice(0, 200);
    }
  }
  return out;
}

/**
 * Build `docs/systems/README.md` content from on-disk artifacts. Pure
 * string assembly so tests can assert against the output without I/O.
 */
export function buildCompositeReadme(repoRoot) {
  const hypPath = join(repoRoot, 'docs/systems/_hypothesis.md');
  if (!existsSync(hypPath)) {
    throw new Error(`composite needs ${hypPath}; run \`hypothesis\` or \`run\` first.`);
  }
  const systems = filterValidConsumes(parseHypothesis(readFileSync(hypPath, 'utf8')));
  const summaries = readManifestSummaries(repoRoot);
  systems.sort((a, b) => a.name.localeCompare(b.name));

  const repo = repoMeta(repoRoot);
  const parts = [
    HEADER,
    '',
    `# Systems Registry — ${repo.name}`,
    '',
    'Index of **complex systems** in this repo — coordinated multi-file pipelines',
    'whose pieces span disjoint dirs and whose loops close back into something',
    '(the dashboard, CI, the user, a future LLM turn).',
    '',
    'Each file here is a manifest with YAML front-matter (`name`, `summary`,',
    '`globs`, `inject` config) plus a markdown body (loop diagram + anchors +',
    'invariants + failure modes). A PreToolUse hook in `.claude/settings.json`',
    'matches the path Claude is about to touch against every system\'s globs and',
    'injects the matching system\'s Mermaid + page link into the next LLM turn.',
    '',
    'Source of truth for detection rules: `tools/systems-registry/detect.mjs`.',
    '',
    '## How these systems feed each other',
    '',
    renderCompositeMermaid(systems),
    '',
    '## Quick reference',
    '',
    '| System | Summary |',
    '|---|---|',
  ];
  for (const s of systems) {
    const sum = (summaries[s.name] || s.summary || '').replace(/\|/g, '\\|');
    parts.push(`| [${s.name}](${s.name}.md) | ${sum} |`);
  }
  parts.push('');
  return parts.join('\n');
}

/** Write the composite README. Returns { path, systems, edges }. */
export function writeCompositeReadme(repoRoot) {
  const content = buildCompositeReadme(repoRoot);
  const outPath = join(repoRoot, 'docs/systems/README.md');
  writeFileSync(outPath, content);
  const systems = filterValidConsumes(parseHypothesis(readFileSync(join(repoRoot, 'docs/systems/_hypothesis.md'), 'utf8')));
  const edges = systems.reduce((n, s) => n + s.consumes.length, 0);
  return { path: outPath, systems: systems.length, edges };
}
