import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { detect, _internal } from './detect.mjs';

function fixture(spec) {
  const root = mkdtempSync(join(tmpdir(), 'sr-detect-'));
  for (const [path, body] of Object.entries(spec)) {
    const full = join(root, path);
    mkdirSync(join(full, '..'), { recursive: true });
    writeFileSync(full, body);
  }
  return root;
}

describe('signalCoordinator', () => {
  it('fires when a top-level file imports >=2 siblings', () => {
    const root = fixture({
      'tools/loop/run.mjs': "import { capture } from './capture.mjs';\nimport { score } from './score.mjs';\n",
      'tools/loop/capture.mjs': 'export const capture = () => {};\n',
      'tools/loop/score.mjs': 'export const score = () => {};\n',
    });
    try {
      const r = _internal.scoreDir(join(root, 'tools/loop'), root);
      assert.equal(r.signals.coordinator, true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('handles Python-style imports without `from`', () => {
    const root = fixture({
      'pkg/main.py': 'import sibling_a\nimport sibling_b\nx = 1\n',
      'pkg/sibling_a.py': 'a = 1\n',
      'pkg/sibling_b.py': 'b = 1\n',
    });
    try {
      const r = _internal.scoreDir(join(root, 'pkg'), root);
      assert.equal(r.signals.coordinator, true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('does not fire when no siblings imported', () => {
    const root = fixture({
      'pkg/a.mjs': 'export const a = 1;\n',
      'pkg/b.mjs': 'export const b = 2;\n',
      'pkg/c.mjs': 'export const c = 3;\n',
    });
    try {
      const r = _internal.scoreDir(join(root, 'pkg'), root);
      assert.equal(r.signals.coordinator, false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe('signalLoop', () => {
  it('fires on filename hint (*_loop.py)', () => {
    const root = fixture({ 'pkg/price_loop.py': 'x = 1\n' });
    try {
      const r = _internal.scoreDir(join(root, 'pkg'), root);
      assert.equal(r.signals.loop, true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fires on --until-done flag', () => {
    const root = fixture({ 'pkg/cli.mjs': "if (args.includes('--until-done')) {}\n" });
    try {
      const r = _internal.scoreDir(join(root, 'pkg'), root);
      assert.equal(r.signals.loop, true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('fires on while True', () => {
    const root = fixture({ 'pkg/x.py': 'while True:\n    pass\n' });
    try {
      const r = _internal.scoreDir(join(root, 'pkg'), root);
      assert.equal(r.signals.loop, true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe('signalSpecOrReadme', () => {
  it('counts hand-written README', () => {
    const root = fixture({ 'pkg/README.md': '# hand-written\nthis is a real readme' });
    try {
      const r = _internal.scoreDir(join(root, 'pkg'), root);
      assert.equal(r.signals['spec-or-readme'], true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('rejects docgen-generated READMEs (marker at top)', () => {
    const root = fixture({ 'pkg/README.md': '<!-- auto-generated by docgen -->\nbody' });
    try {
      const r = _internal.scoreDir(join(root, 'pkg'), root);
      assert.equal(r.signals['spec-or-readme'], false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('does NOT reject when the marker is only mentioned in prose', () => {
    const root = fixture({ 'pkg/README.md': '# my tool\n\nthis writes READMEs with "auto-generated by docgen" marker.\n' });
    try {
      const r = _internal.scoreDir(join(root, 'pkg'), root);
      assert.equal(r.signals['spec-or-readme'], true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('counts ALL_CAPS docs', () => {
    const root = fixture({ 'pkg/PRICE_MODELING.md': '# modelling' });
    try {
      const r = _internal.scoreDir(join(root, 'pkg'), root);
      assert.equal(r.signals['spec-or-readme'], true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe('detect (end-to-end)', () => {
  it('finds a system that hits >=4 signals', () => {
    const root = fixture({
      'tools/example/run.mjs':
        `import { spawn } from 'node:child_process';\n` +
        `import { capture } from './capture.mjs';\n` +
        `import { score } from './score.mjs';\n` +
        `while (true) {\n  spawn('claude', ['-p']);\n}\n` +
        `import { writeFileSync } from 'fs';\nwriteFileSync('state.json', '{}');\n`,
      'tools/example/capture.mjs': 'export const capture = () => {};\n',
      'tools/example/score.mjs': 'export const score = () => {};\n',
      'tools/example/run.test.mjs': "import { test } from 'node:test';\ntest('a', () => {});",
      'tools/example/capture.test.mjs': "import { test } from 'node:test';\ntest('b', () => {});",
      'tools/example/score.test.mjs': "import { test } from 'node:test';\ntest('c', () => {});",
      'tools/example/README.md': '# example tool',
    });
    try {
      const found = detect(root);
      assert.ok(found.length >= 1);
      const ex = found.find(s => s.dir === 'tools/example');
      assert.ok(ex, 'tools/example should be detected');
      assert.ok(ex.score >= 4);
      assert.ok(ex.signals.includes('coordinator'));
      assert.ok(ex.signals.includes('persistent-state'));
      assert.ok(ex.signals.includes('loop'));
      assert.ok(ex.signals.includes('subprocess'));
      assert.ok(ex.signals.includes('tests'));
      assert.ok(ex.signals.includes('spec-or-readme'));
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('rejects a small utility library (score < 4)', () => {
    const root = fixture({
      'packages/util/index.mjs': "export const add = (a,b) => a+b;\nexport const sub = (a,b) => a-b;\n",
      'packages/util/README.md': '# util',
    });
    try {
      const found = detect(root);
      const util = found.find(s => s.dir === 'packages/util');
      assert.equal(util, undefined, 'small util lib should NOT be detected');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
