import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  readAnchorFiles,
  readPriorManifest,
  gatherInputsFor,
  buildPromptFor,
  generateBody,
  stampAutoGenerated,
  selectAnchorFiles,
  scoreFilename,
  extractAnchorPathsFromManifest,
  computeAdaptiveCap,
  _internal,
} from './pass2.mjs';

function makeFixture() {
  const root = mkdtempSync(join(tmpdir(), 'sr-pass2-'));
  mkdirSync(join(root, 'apps/foo'), { recursive: true });
  writeFileSync(join(root, 'apps/foo/run.mjs'), "export const runFoo = () => {};\n");
  writeFileSync(join(root, 'apps/foo/capture.mjs'), "export const capture = () => ({});\n");
  return root;
}

describe('expandGlobs', () => {
  it('expands dir/** patterns', () => {
    const root = makeFixture();
    try {
      const files = _internal.expandGlobs(root, ['apps/foo/**']);
      assert.ok(files.includes('apps/foo/run.mjs'));
      assert.ok(files.includes('apps/foo/capture.mjs'));
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('handles explicit file paths', () => {
    const root = makeFixture();
    try {
      const files = _internal.expandGlobs(root, ['apps/foo/run.mjs']);
      assert.deepEqual(files, ['apps/foo/run.mjs']);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('returns empty for non-existent globs', () => {
    const root = makeFixture();
    try {
      const files = _internal.expandGlobs(root, ['nope/**']);
      assert.deepEqual(files, []);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

describe('readAnchorFiles', () => {
  it('reads files capped at byte limit', () => {
    const root = makeFixture();
    try {
      const anchors = readAnchorFiles(root, ['apps/foo/run.mjs']);
      assert.equal(anchors.length, 1);
      assert.match(anchors[0].content, /runFoo/);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

describe('readPriorManifest', () => {
  it('returns null when no prior manifest', () => {
    const root = makeFixture();
    try {
      assert.equal(readPriorManifest(root, 'apps-foo'), null);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('reads existing prior manifest', () => {
    const root = makeFixture();
    mkdirSync(join(root, 'docs/systems'), { recursive: true });
    writeFileSync(join(root, 'docs/systems/apps-foo.md'), '---\nname: apps-foo\n---\nbody');
    try {
      const m = readPriorManifest(root, 'apps-foo');
      assert.match(m, /name: apps-foo/);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

describe('gatherInputsFor + buildPromptFor', () => {
  it('full pipeline assembles a prompt with hypothesis + anchors + (optional) prior', () => {
    const root = makeFixture();
    try {
      const inputs = gatherInputsFor(root, {
        name: 'apps-foo',
        summary: 'the foo system',
        globs: ['apps/foo/**'],
      });
      assert.equal(inputs.anchors.length, 2);
      assert.equal(inputs.priorManifest, null);
      const prompt = buildPromptFor(inputs);
      assert.match(prompt, /Hypothesis entry/);
      assert.match(prompt, /apps-foo/);
      assert.match(prompt, /Anchor files/);
      assert.match(prompt, /runFoo/);
      assert.match(prompt, /Your task/);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('includes prior manifest section when one exists', () => {
    const root = makeFixture();
    mkdirSync(join(root, 'docs/systems'), { recursive: true });
    writeFileSync(join(root, 'docs/systems/apps-foo.md'), '---\nname: apps-foo\n---\nprior body');
    try {
      const inputs = gatherInputsFor(root, { name: 'apps-foo', globs: ['apps/foo/**'] });
      const prompt = buildPromptFor(inputs);
      assert.match(prompt, /Prior manifest/);
      assert.match(prompt, /prior body/);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('does not truncate a prior subflow that sits past the old 4000-char cap', () => {
    const root = makeFixture();
    mkdirSync(join(root, 'docs/systems'), { recursive: true });
    // Real manifests run ~18KB with `## Subflow:` sections near the end.
    // Pad past the old 4000-char cutoff, then place the subflow after it.
    const padding = '\n' + 'x'.repeat(8000) + '\n';
    const prior = `---\nname: apps-foo\n---\n# apps-foo${padding}## Subflow: late-flow\n\n\`\`\`mermaid\nflowchart LR\n  A --> B\n\`\`\`\n`;
    writeFileSync(join(root, 'docs/systems/apps-foo.md'), prior);
    try {
      const inputs = gatherInputsFor(root, { name: 'apps-foo', globs: ['apps/foo/**'] });
      const prompt = buildPromptFor(inputs);
      // The late subflow must reach the model — this is the richness-regression fix.
      assert.match(prompt, /## Subflow: late-flow/);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

describe('generateBody with injected runner', () => {
  it('writes the manifest to docs/systems/<name>.md', async () => {
    const root = makeFixture();
    try {
      const mockBody = '---\nname: apps-foo\nstatus: active\n---\n\n# apps-foo\n\nbody content';
      const runner = async () => mockBody;
      const r = await generateBody(root, { name: 'apps-foo', globs: ['apps/foo/**'] }, { runner });
      assert.ok(r.outPath);
      assert.ok(existsSync(r.outPath));
      assert.match(readFileSync(r.outPath, 'utf8'), /apps-foo/);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('write: false skips writing', async () => {
    const root = makeFixture();
    try {
      const runner = async () => 'body';
      const r = await generateBody(root, { name: 'apps-foo', globs: ['apps/foo/**'] }, { runner, write: false });
      assert.equal(r.outPath, null);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('strips code-fence wrapping if LLM emitted it', async () => {
    const root = makeFixture();
    try {
      const wrapped = '```markdown\n---\nname: x\n---\n\nbody\n```';
      const runner = async () => wrapped;
      const r = await generateBody(root, { name: 'x', globs: ['apps/foo/**'] }, { runner });
      assert.doesNotMatch(r.body, /^```/);
      assert.match(r.body, /name: x/);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

describe('stripCodeFence', () => {
  it('removes ```markdown wrapping', () => {
    const out = _internal.stripCodeFence('```markdown\nhello\n```');
    assert.equal(out, 'hello');
  });
  it('removes plain ``` wrapping', () => {
    const out = _internal.stripCodeFence('```\nhello\n```');
    assert.equal(out, 'hello');
  });
  it('leaves unwrapped text alone', () => {
    assert.equal(_internal.stripCodeFence('plain'), 'plain');
  });
});

describe('stripCodeFence robustness (preamble + fence)', () => {
  it('extracts manifest from a fenced block even with LLM preamble', () => {
    const resp = 'The file exists, here is the revised manifest:\n\n```markdown\n---\nname: x\nstatus: active\n---\n\n# x\n\nbody\n```\n';
    const out = _internal.stripCodeFence(resp);
    assert.ok(out.startsWith('---'));
    assert.match(out, /name: x/);
    assert.doesNotMatch(out, /revised manifest/);
  });
  it('slices from front-matter when there is preamble but no fence', () => {
    const resp = 'Here you go:\n---\nname: y\n---\n\nbody';
    const out = _internal.stripCodeFence(resp);
    assert.ok(out.startsWith('---'));
    assert.match(out, /name: y/);
  });
});

describe('scoreFilename', () => {
  it('promotes READMEs above plain source', () => {
    assert.ok(scoreFilename('foo/README.md') > scoreFilename('foo/bar.ts'));
  });
  it('promotes handlers and routes', () => {
    assert.ok(scoreFilename('foo/userHandler.ts') > scoreFilename('foo/util.ts'));
    assert.ok(scoreFilename('foo/userRoutes.ts') > scoreFilename('foo/util.ts'));
    assert.ok(scoreFilename('agents/execute_billing/handler.rs') > scoreFilename('agents/execute_billing/util.rs'));
  });
  it('promotes services / writers / parsers / strategies', () => {
    assert.ok(scoreFilename('foo/billingParser.ts') > scoreFilename('foo/util.ts'));
    assert.ok(scoreFilename('strategies/yield_maximizer/strategy_impl.rs') > scoreFilename('foo/util.rs'));
  });
  it('demotes tests', () => {
    assert.ok(scoreFilename('foo/x.test.ts') < scoreFilename('foo/x.ts'));
    assert.ok(scoreFilename('foo/x_test.rs') < scoreFilename('foo/x.rs'));
  });
  it('demotes .d.ts and config files', () => {
    assert.ok(scoreFilename('foo/types.d.ts') < 0);
    assert.ok(scoreFilename('foo/jest.config.ts') < 0);
  });
  it('boosts mod.rs / lib.rs as module roots', () => {
    assert.ok(scoreFilename('foo/mod.rs') > scoreFilename('foo/leaf.rs'));
    assert.ok(scoreFilename('foo/lib.rs') > scoreFilename('foo/leaf.rs'));
  });
});

describe('selectAnchorFiles (round-robin)', () => {
  function multiGlobFixture() {
    const root = mkdtempSync(join(tmpdir(), 'sr-rr-'));
    // Three globs, each with several files, designed to mimic the
    // billing-engine layout where alphabetical-first would starve the
    // 'apps/backend/...' bucket entirely.
    mkdirSync(join(root, 'apps/api'), { recursive: true });
    mkdirSync(join(root, 'apps/backend/programs/example/src/instructions/agents'), { recursive: true });
    mkdirSync(join(root, 'apps/web/src/components'), { recursive: true });
    // api bucket — 5 files
    for (const f of ['handler.ts', 'service.ts', 'helper1.ts', 'helper2.ts', 'util.ts']) {
      writeFileSync(join(root, 'apps/api', f), `// ${f}\n`);
    }
    // backend bucket — 4 files
    for (const f of ['handler.rs', 'mod.rs', 'util.rs', 'helper.rs']) {
      writeFileSync(join(root, 'apps/backend/programs/example/src/instructions/agents', f), `// ${f}\n`);
    }
    // web bucket — 3 files
    for (const f of ['Component.tsx', 'helper.ts', 'README.md']) {
      writeFileSync(join(root, 'apps/web/src/components', f), `// ${f}\n`);
    }
    return root;
  }

  it('contributes at least one file from every glob with matches', () => {
    const root = multiGlobFixture();
    try {
      const picked = selectAnchorFiles(root, [
        'apps/api/**',
        'apps/backend/programs/example/src/instructions/agents/**',
        'apps/web/src/components/**',
      ], { maxFiles: 6 });
      assert.equal(picked.length, 6);
      assert.ok(picked.some(p => p.startsWith('apps/api/')), 'has api');
      assert.ok(picked.some(p => p.startsWith('apps/backend/')), 'has backend — the bug we fixed');
      assert.ok(picked.some(p => p.startsWith('apps/web/')), 'has web');
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('prioritizes high-score files (handler / README) within each bucket', () => {
    const root = multiGlobFixture();
    try {
      const picked = selectAnchorFiles(root, [
        'apps/api/**',
        'apps/web/src/components/**',
      ], { maxFiles: 4 });
      // Round-robin gives [api[0], web[0], api[1], web[1]]; the top of
      // each bucket should be the boosted file.
      const apiPicks = picked.filter(p => p.startsWith('apps/api/'));
      const webPicks = picked.filter(p => p.startsWith('apps/web/'));
      assert.equal(apiPicks[0], 'apps/api/handler.ts', 'api bucket leads with handler');
      assert.equal(webPicks[0], 'apps/web/src/components/README.md', 'web bucket leads with README');
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('respects maxFiles cap and deduplicates across overlapping globs', () => {
    const root = multiGlobFixture();
    try {
      // Same dir referenced twice — total picks must still be capped and
      // each file appears at most once.
      const picked = selectAnchorFiles(root, [
        'apps/api/**',
        'apps/api/**',
      ], { maxFiles: 3 });
      assert.equal(picked.length, 3);
      assert.equal(new Set(picked).size, 3, 'no duplicates');
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('is deterministic on identical inputs', () => {
    const root = multiGlobFixture();
    try {
      const a = selectAnchorFiles(root, ['apps/api/**', 'apps/web/src/components/**'], { maxFiles: 4 });
      const b = selectAnchorFiles(root, ['apps/api/**', 'apps/web/src/components/**'], { maxFiles: 4 });
      assert.deepEqual(a, b);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('returns empty list when no globs match', () => {
    const root = mkdtempSync(join(tmpdir(), 'sr-rr-empty-'));
    try {
      const picked = selectAnchorFiles(root, ['nope/**'], { maxFiles: 10 });
      assert.deepEqual(picked, []);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

describe('computeAdaptiveCap', () => {
  it('respects floor for small/zero glob counts', () => {
    assert.equal(computeAdaptiveCap(0), 15);
    assert.equal(computeAdaptiveCap(1), 15);
    assert.equal(computeAdaptiveCap(5), 15); // 5*2=10, floor=15
  });
  it('scales linearly in the middle', () => {
    assert.equal(computeAdaptiveCap(8), 16);
    assert.equal(computeAdaptiveCap(13), 26); // billing-engine
  });
  it('caps at ceiling for very large systems', () => {
    assert.equal(computeAdaptiveCap(20), 35);
    assert.equal(computeAdaptiveCap(100), 35);
  });
});

describe('extractAnchorPathsFromManifest', () => {
  it('pulls backtick-quoted source paths from manifest body', () => {
    const body = [
      '## Anchors',
      '- `apps/api/src/handlers/userHandler.ts` — does X',
      '- `apps/backend/programs/foo/src/handler.rs:42` — Rust handler with line ref',
      '- some prose with `apps/web/src/App.tsx#L10` and a `not-a-path` token',
    ].join('\n');
    const paths = extractAnchorPathsFromManifest(body);
    assert.ok(paths.includes('apps/api/src/handlers/userHandler.ts'));
    assert.ok(paths.includes('apps/backend/programs/foo/src/handler.rs'));
    assert.ok(paths.includes('apps/web/src/App.tsx'));
    assert.ok(!paths.some(p => p.includes('not-a-path')));
  });
  it('returns empty for empty/null input', () => {
    assert.deepEqual(extractAnchorPathsFromManifest(''), []);
    assert.deepEqual(extractAnchorPathsFromManifest(null), []);
  });
  it('deduplicates repeated mentions', () => {
    const body = '`a/b.ts` and again `a/b.ts:foo` and once more `a/b.ts#L1`';
    const paths = extractAnchorPathsFromManifest(body);
    assert.deepEqual(paths, ['a/b.ts']);
  });
});

describe('selectAnchorFiles with priorAnchorPaths', () => {
  it('boosts files cited in the prior manifest above filename heuristics', () => {
    const root = mkdtempSync(join(tmpdir(), 'sr-prior-'));
    try {
      mkdirSync(join(root, 'apps/lib'), { recursive: true });
      // util.ts: filename score 0; the prior manifest mentions it.
      // handler.ts: filename score 8; no prior mention.
      // Without priorAnchorPaths, handler wins. With priorAnchorPaths,
      // util gets +20 and beats handler.
      writeFileSync(join(root, 'apps/lib/util.ts'), '// util');
      writeFileSync(join(root, 'apps/lib/handler.ts'), '// handler');
      const noPrior = selectAnchorFiles(root, ['apps/lib/**'], { maxFiles: 1 });
      assert.equal(noPrior[0], 'apps/lib/handler.ts');
      const withPrior = selectAnchorFiles(root, ['apps/lib/**'], { maxFiles: 1, priorAnchorPaths: ['apps/lib/util.ts'] });
      assert.equal(withPrior[0], 'apps/lib/util.ts');
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

describe('stampAutoGenerated', () => {
  it('inserts the warning comment right after the front-matter', () => {
    const body = '---\nname: x\n---\n\n# heading\n';
    const out = stampAutoGenerated(body);
    assert.match(out, /---\n<!-- auto-generated by systems-registry/);
    assert.match(out, /# heading/);
    // Front-matter still parses (starts at offset 0, comment is BELOW the close)
    assert.ok(out.startsWith('---\nname: x\n---\n'));
  });
  it('is idempotent — already-stamped bodies pass through unchanged', () => {
    const body = '---\nname: x\n---\n<!-- auto-generated by systems-registry — do not hand-edit -->\n# heading\n';
    const out = stampAutoGenerated(body);
    assert.equal(out, body);
  });
  it('leaves bodies without front-matter alone', () => {
    const body = '# raw markdown\n';
    assert.equal(stampAutoGenerated(body), body);
  });
});
