#!/usr/bin/env node
/**
 * systems-registry — Pass 1: hypothesis pass.
 *
 * The LLM synthesis layer above Pass 0's heuristic detector. Reads
 * fresh inputs only (auto-updated abstractions + source code + system's
 * own prior output), assembles a prompt, calls `claude -p`, and writes
 * the structured result to docs/systems/_hypothesis.md.
 *
 * Design contract: docs/superpowers/specs/2026-05-25-systems-registry-hypothesis-pass.md
 *
 * Inputs the prompt sees (FRESH SOURCES ONLY per the spec):
 *   - Pass 0 candidate list (fresh per run)
 *   - docgen-generated READMEs — Purpose + Map sections only
 *   - Coordinator file snippets (first 4 KB of top file per candidate)
 *   - Import / cross-tree graph between candidates
 *   - Recent git log per candidate dir
 *   - Prior _hypothesis.md if exists
 *   - Prior docs/systems/X.md manifests if exist
 *
 * Dropped: ARCHITECTURE.md, DATA-LAYOUT.md, SECURITY.md, root README,
 * CLAUDE.md sidecars, specs/. Hand-written docs can lie.
 *
 * Output: docs/systems/_hypothesis.md with YAML front-matter listing each
 * synthesized system + summary + globs + closing-arrow target + consumes.
 *
 * The runner (which actually calls claude -p) is dependency-injected so
 * tests stay hermetic. Same pattern as docgen.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { execFileSync, spawn } from 'node:child_process';

import { detect } from './detect.mjs';
import { withRetry } from './llm-retry.mjs';

const PRIOR_HYPOTHESIS_PATH = 'docs/systems/_hypothesis.md';
// Per-repo context injection — a hand-written, in-repo file the consumer
// uses to add domain context the canonical tool can't know about (their
// vocabulary, dirs to ignore, the system boundaries they care about). The
// tool ships canonical and never embeds repo-specific knowledge; the
// consumer ships THIS file when they want to tilt the hypothesis their way.
// Lives alongside _hypothesis.md / _categories.json with the same `_`
// convention so users discover it naturally.
const REPO_CONTEXT_PATH = 'docs/systems/_context.md';
const DOCGEN_MARKER = 'auto-generated by docgen';

/**
 * Pull just the Purpose + Map sections from a docgen-generated README.
 * These are the curated summaries; the rest is per-file detail that's
 * already covered by the heuristic candidate list.
 */
export function extractDocgenSummary(readmeText) {
  if (!readmeText) return '';
  // docgen READMEs start with the marker; if not present, treat as
  // hand-written and skip entirely (per spec: don't ground in hand-written).
  const firstLine = readmeText.split('\n', 1)[0];
  if (!firstLine.includes(DOCGEN_MARKER)) return '';
  const lines = readmeText.split('\n');
  const out = [];
  let inSection = false;
  for (const line of lines) {
    if (line.startsWith('## Purpose') || line.startsWith('## Map')) {
      inSection = true;
      out.push(line);
      continue;
    }
    if (line.startsWith('## ') && inSection) {
      inSection = false;
      continue;
    }
    if (inSection) out.push(line);
  }
  return out.join('\n').trim();
}

/**
 * Get recent git log for a directory. Last 10 commits, oneline format.
 * Returns empty string if git unavailable or dir not in a repo.
 */
function gitLogFor(repoRoot, relDir) {
  try {
    const out = execFileSync(
      'git', ['-C', repoRoot, 'log', '--oneline', '-n', '10', '--', relDir],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }
    );
    return out.trim();
  } catch {
    return '';
  }
}

/**
 * First 4 KB of the coordinator file for a candidate. Picks the file with
 * the most "sibling reference" weight (the one that imports the most other
 * files in the same dir — that's almost always the orchestrator).
 */
function coordinatorSnippet(candidate, repoRoot) {
  const dir = resolve(repoRoot, candidate.dir);
  if (!existsSync(dir)) return '';
  // Heuristic: pick the file whose basename signals it's the coordinator —
  // 'run', 'main', 'cli', 'index', 'orchestrate', 'coordinator', 'server' for
  // JS/Py; 'mod', 'lib', 'handler' for Rust (mod.rs/lib.rs declare a module's
  // pieces, *_handler.rs is the Anchor instruction entry point). Else
  // lexicographic first.
  const files = readdirSync(dir).filter(f => /\.(ts|mjs|js|py|rs|go)$/.test(f));
  const ranked = files.sort((a, b) => {
    const score = name => /\b(run|main|cli|index|orchestrate|coordinator|server|mod|lib|handler)\b/i.test(name) ? -1 : 1;
    return score(a) - score(b);
  });
  if (ranked.length === 0) return '';
  try {
    const content = readFileSync(join(dir, ranked[0]), 'utf8').slice(0, 4096);
    return `// ${candidate.dir}/${ranked[0]}\n${content}`;
  } catch {
    return '';
  }
}

/**
 * Existing system manifests treated as "previously validated knowledge".
 * Read raw front-matter + the What-it-does section. Pass 1 uses these as
 * "what we previously concluded — is it still true?"
 */
function priorSystemManifests(repoRoot) {
  const dir = join(repoRoot, 'docs', 'systems');
  if (!existsSync(dir)) return [];
  const out = [];
  for (const name of readdirSync(dir)) {
    if (!name.endsWith('.md') || name === 'README.md' || name.startsWith('_')) continue;
    try {
      const text = readFileSync(join(dir, name), 'utf8');
      // Grab front-matter (between --- markers) + first ## section
      const m = text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*?)(?:\n## (?!What)|\n##\s*$|$)/);
      if (m) out.push({ name: name.replace(/\.md$/, ''), frontMatter: m[1], summary: m[2].trim() });
    } catch { /* skip */ }
  }
  return out;
}

/**
 * Import graph edges between candidate dirs. For each candidate, count
 * how many of its files import from each OTHER candidate's path.
 */
function importGraph(candidates, repoRoot) {
  const edges = [];
  for (const a of candidates) {
    const aDir = resolve(repoRoot, a.dir);
    if (!existsSync(aDir)) continue;
    for (const b of candidates) {
      if (a === b) continue;
      // Count files in `a` that mention `b.dir` in their text
      let count = 0;
      const files = readdirSync(aDir).filter(f => /\.(ts|mjs|js|py|rs|go)$/.test(f));
      for (const f of files) {
        try {
          const c = readFileSync(join(aDir, f), 'utf8');
          if (c.includes(b.dir)) count++;
        } catch { /* skip */ }
      }
      if (count > 0) edges.push({ from: a.name, to: b.name, weight: count });
    }
  }
  return edges;
}

// ─── reality signals beyond Pass-0 candidates ─────────────────────────
// The candidate list is detector-grade — it misses single-file deployed
// services, brand-new cross-cutting products, and code domains that are
// pure business logic with no loop/hook/coordinator signal. These extra
// signal sources tell the LLM what EXISTS in the repo so it can spot
// systems the heuristic walked right past.

/**
 * Walk a YAML-ish file for Render service entries. A service entry starts
 * with `  - type: <web|cron|worker|...>` under `services:` (Render's
 * canonical layout), or with `  - name:` in older variants. We track the
 * indent of the `-` to know when the entry ends — any subsequent line at
 * that same or shallower indent terminates the service block.
 */
export function parseRenderYaml(text) {
  const out = [];
  let current = null;
  let currentIndent = null;   // column of the `-` that started this entry
  let inServices = false;
  for (const line of text.split('\n')) {
    if (/^services:\s*$/.test(line)) { inServices = true; continue; }
    if (!inServices) continue;
    let m;
    // Start-of-entry: `  - type: X` OR `  - name: X`
    if ((m = line.match(/^(\s*)-\s+(type|name):\s*(\S+)/))) {
      if (current && (current.type || current.schedule)) out.push(current);
      currentIndent = m[1].length;
      current = { type: '', name: '', schedule: '' };
      current[m[2]] = m[3].trim().replace(/^["']|["']$/g, '');
      continue;
    }
    if (!current) continue;
    // Top-level YAML key (e.g. `envVarGroups:`) ends the services block.
    if (/^[A-Za-z]/.test(line)) { if (current) { if (current.type || current.schedule) out.push(current); current = null; } inServices = false; continue; }
    // Lines at or shallower than the entry's `-` mean we left the entry.
    const leadingSpaces = line.match(/^(\s*)\S/);
    if (leadingSpaces && leadingSpaces[1].length <= currentIndent && line.trim()) {
      // But it could be another `- type:` for the NEXT service — handled
      // by the start-of-entry match above on next iteration. Here we just
      // close the current one if the new line isn't a property under it.
      if (!/^\s*-/.test(line)) {
        if (current.type || current.schedule) out.push(current);
        current = null;
        continue;
      }
    }
    // Field lines — only count properties indented STRICTLY MORE than the `-`.
    const indent = (line.match(/^(\s*)/) || ['', ''])[1].length;
    if (indent <= currentIndent) continue;
    if ((m = line.match(/^\s+name:\s*(\S+)/)) && !current.name) current.name = m[1].trim().replace(/^["']|["']$/g, '');
    if ((m = line.match(/^\s+type:\s*(\S+)/)) && !current.type) current.type = m[1].trim().replace(/^["']|["']$/g, '');
    if ((m = line.match(/^\s+schedule:\s*["']?([^"'\n#]+?)["']?\s*(#|$)/)) && !current.schedule) current.schedule = m[1].trim();
    if ((m = line.match(/^\s+rootDir:\s*(\S+)/))) current.rootDir = m[1].trim();
  }
  if (current && (current.type || current.schedule)) out.push(current);
  // Real service types only; drops env-var-group entries.
  return out.filter(s => /^(web|cron|worker|static_site|web_service|background_worker)$/.test(s.type));
}

/**
 * Deployed services declared in any deployment manifest the repo uses.
 * The point of this signal is to tell the LLM what's actually RUNNING in
 * production — a single-file cron whose only on-disk fingerprint is a
 * service block in one of these files would otherwise be invisible to
 * the systems map.
 *
 * Currently handles Render (`render.yaml`). When new manifest formats are
 * added (Fly.io `fly.toml`, Vercel `vercel.json`, k8s manifests, etc.),
 * add a parser branch here — the prompt section that consumes this list
 * doesn't care about the source format.
 */
function deployedServices(repoRoot) {
  const out = [];
  function walk(dir, depth = 0) {
    if (depth > 3) return;
    let entries = [];
    try { entries = readdirSync(dir); } catch { return; }
    for (const ent of entries) {
      if (ent.startsWith('.') || ent === 'node_modules') continue;
      const full = join(dir, ent);
      try {
        const st = statSync(full);
        if (st.isDirectory()) { walk(full, depth + 1); continue; }
        // Render
        if (ent === 'render.yaml' || ent === 'render.yml') {
          for (const s of parseRenderYaml(readFileSync(full, 'utf8'))) {
            s.platform = 'render'; s.file = relative(repoRoot, full); out.push(s);
          }
        }
        // Fly.io — a fly.toml file declares ONE app named by `app = "..."`.
        if (ent === 'fly.toml') {
          const text = readFileSync(full, 'utf8');
          const m = text.match(/^\s*app\s*=\s*["']([^"']+)["']/m);
          if (m) out.push({ platform: 'fly', name: m[1], type: 'web', schedule: '', file: relative(repoRoot, full) });
        }
      } catch { /* skip */ }
    }
  }
  walk(repoRoot);
  return out;
}

/**
 * Every immediate dir under `apps/` (and `tools/`, `packages/`) plus its
 * one-line description from its own README — regardless of whether the
 * detector picked it up. This catches single-file services (a one-file
 * `apps/<name>/index.ts` cron with a README, detector score 0) and lets
 * the LLM see "there's an app here, what system covers it?"
 */
function topLevelApps(repoRoot) {
  const out = [];
  const roots = ['apps', 'tools', 'packages'];
  for (const r of roots) {
    const rp = join(repoRoot, r);
    if (!existsSync(rp)) continue;
    for (const ent of readdirSync(rp, { withFileTypes: true })) {
      if (!ent.isDirectory() || ent.name.startsWith('.') || ent.name === 'node_modules') continue;
      const dir = `${r}/${ent.name}`;
      const readmePath = join(rp, ent.name, 'README.md');
      let desc = '';
      if (existsSync(readmePath)) {
        try {
          const c = readFileSync(readmePath, 'utf8').slice(0, 4096);
          // First non-heading, non-empty paragraph — works for both docgen
          // (## Purpose ...) and hand-written (# Title \n description).
          const purpose = c.match(/##\s+Purpose\s*\n+([^\n#]+(?:\n[^\n#]+)*)/i);
          if (purpose) desc = purpose[1].trim();
          else {
            const para = c.split(/\n#/)[1] || c;
            const first = para.split('\n').filter(l => l.trim() && !l.startsWith('#') && !l.startsWith('---'))[0] || '';
            desc = first.slice(0, 200);
          }
        } catch { /* ignore */ }
      }
      out.push({ dir, desc: desc.replace(/\s+/g, ' ').slice(0, 200) });
    }
  }
  return out;
}

/**
 * Database tables — extracted from SQL migration files. Cross-cutting
 * data products (a table written by one cron, read by an API endpoint,
 * rendered by a frontend page) are exactly the systems the detector
 * misses; surfacing the table list lets the LLM connect those pieces.
 */
function dbTables(repoRoot) {
  const tables = new Set();
  function walk(dir, depth = 0) {
    if (depth > 4) return;
    let entries = [];
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const ent of entries) {
      if (ent.name.startsWith('.') || ent.name === 'node_modules') continue;
      const full = join(dir, ent.name);
      if (ent.isDirectory()) {
        if (/migrations?|sql/i.test(ent.name)) walk(full, depth + 1);
        else if (depth < 2) walk(full, depth + 1);
      } else if (ent.isFile() && /\.sql$/.test(ent.name)) {
        try {
          const c = readFileSync(full, 'utf8');
          for (const m of c.matchAll(/CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+["`]?(\w+)["`]?/gi)) {
            tables.add(m[1]);
          }
        } catch { /* skip */ }
      }
    }
  }
  walk(repoRoot);
  return [...tables].sort();
}

/**
 * HTTP route / handler surface — file basenames of likely endpoint
 * definitions. Routes themselves rarely score on the detector (no loop,
 * no hook, no subprocess), so a routes-rooted system (e.g. one whose
 * scope is the routes + the services it dispatches to + the frontend
 * that consumes it) needs a dedicated signal.
 *
 * Heuristic — any path segment matching `routes` / `handlers` / `api` /
 * `controllers`, then list files with framework-suggestive basenames
 * (`*Routes.ts`, `*Handler.ts`, `*Controller.ts`, files that re-export a
 * router). Catches Fastify, Express, NestJS, FastAPI, Flask, Rails-ish.
 */
function httpSurface(repoRoot) {
  const SURFACE_DIRS = /^(routes|handlers|controllers|endpoints|views)$/i;
  const SKIP_BASE = /^(index|jest\.config|tsconfig|setup|teardown|globals?|fixtures?|helpers?|utils?|types?|constants?|errors?|schema|schemas|middleware|README|test|tests|__tests__|__snapshots__|force-.*)$/i;
  const NAMING = /(Routes?|Handlers?|Controller|router)$/i;
  const seen = new Set();
  const out = [];
  function walk(dir, depth = 0, parents = []) {
    if (depth > 6) return;
    let entries = [];
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    const parentName = parents[parents.length - 1] || '';
    const immediateParentIsSurface = SURFACE_DIRS.test(parentName);
    for (const ent of entries) {
      if (ent.name.startsWith('.') || ent.name === 'node_modules' || ent.name === 'dist') continue;
      const full = join(dir, ent.name);
      if (ent.isDirectory()) walk(full, depth + 1, [...parents, ent.name]);
      else if (ent.isFile() && immediateParentIsSurface) {
        if (!/\.(ts|tsx|mjs|js|py|go|rb)$/.test(ent.name)) continue;
        if (/\.test\.|\.spec\.|\.d\.ts$/.test(ent.name)) continue;
        const base = ent.name.replace(/\.[^.]+$/, '');
        if (SKIP_BASE.test(base)) continue;
        // Either basename is naming-suggestive, OR the immediate parent is
        // an unambiguous surface dir (`routes/`, `handlers/`…). Skip files
        // in catch-all `api/` dirs unless basename suggests they're routes
        // (api/birdeyeClient.ts is a client, not a route).
        const looks = NAMING.test(base) || (parentName.toLowerCase() !== 'api' && immediateParentIsSurface);
        if (!looks) continue;
        const key = relative(repoRoot, full);
        if (!seen.has(key)) { seen.add(key); out.push(base); }
      }
    }
  }
  walk(repoRoot);
  return out.slice(0, 200);
}

/**
 * Read the optional per-repo `_context.md` if it exists. Returns null when
 * absent — the prompt-builder skips its section entirely so a repo that
 * doesn't ship one sees no change. Capped at 16 KB to bound prompt growth.
 */
function repoContext(repoRoot) {
  const p = join(repoRoot, REPO_CONTEXT_PATH);
  if (!existsSync(p)) return null;
  try {
    const text = readFileSync(p, 'utf8').slice(0, 16 * 1024);
    return text.trim() || null;
  } catch { return null; }
}

/**
 * Read prior _hypothesis.md if it exists. Returns null if absent.
 */
function priorHypothesis(repoRoot) {
  const p = join(repoRoot, PRIOR_HYPOTHESIS_PATH);
  if (!existsSync(p)) return null;
  try { return readFileSync(p, 'utf8'); } catch { return null; }
}

/**
 * Stitch all Tier 1 + Tier 2 inputs into one input object. Pure data
 * gathering — no LLM call. Tests use this directly to assert input
 * shape without mocking the LLM.
 */
export function gatherInputs(repoRoot) {
  const candidates = detect(repoRoot);
  const docgenSummaries = [];
  for (const c of candidates) {
    const readmePath = resolve(repoRoot, c.dir, 'README.md');
    if (existsSync(readmePath)) {
      const summary = extractDocgenSummary(readFileSync(readmePath, 'utf8'));
      if (summary) docgenSummaries.push({ dir: c.dir, summary });
    }
  }
  // Pull docgen summaries for top-level apps too, not just candidates —
  // this is how a single-file deployed service (one-file entrypoint + a
  // README) gets a real description into the prompt despite scoring 0.
  const apps = topLevelApps(repoRoot);
  for (const a of apps) {
    if (docgenSummaries.some(d => d.dir === a.dir)) continue;
    const readmePath = resolve(repoRoot, a.dir, 'README.md');
    if (existsSync(readmePath)) {
      const summary = extractDocgenSummary(readFileSync(readmePath, 'utf8'));
      if (summary) docgenSummaries.push({ dir: a.dir, summary });
    }
  }

  return {
    candidates,
    docgenSummaries,
    coordinatorSnippets: candidates.map(c => ({
      dir: c.dir,
      snippet: coordinatorSnippet(c, repoRoot),
    })).filter(s => s.snippet),
    importGraph: importGraph(candidates, repoRoot),
    gitLogs: candidates.map(c => ({ dir: c.dir, log: gitLogFor(repoRoot, c.dir) })).filter(g => g.log),
    // Reality-signal additions — exist to widen the LLM's view of what's
    // in the repo beyond the detector's score-≥4 lens. Framework-agnostic:
    // pluggable manifest discovery + heuristic route/handler scan.
    deployedServices: deployedServices(repoRoot),
    topLevelApps: apps,
    dbTables: dbTables(repoRoot),
    httpSurface: httpSurface(repoRoot),
    // Per-repo human-authored context. The canonical tool stays repo-
    // agnostic; this is the consumer's hook to inject their own domain
    // knowledge into every regeneration.
    repoContext: repoContext(repoRoot),
    priorHypothesis: priorHypothesis(repoRoot),
    priorSystems: priorSystemManifests(repoRoot),
  };
}

/**
 * Build the LLM prompt from gathered inputs. Pure function — no IO.
 * Tests assert the prompt contains expected sections.
 */
export function buildPrompt(inputs) {
  const parts = [];
  parts.push('You are synthesizing a "complex systems" map for this repository.');
  parts.push('');
  parts.push('A *system* is a coordinated set of files that closes a loop — its');
  parts.push('output flows back into something (the DB, the dashboard, the user,');
  parts.push('the chain, the next LLM turn). It does NOT have to be multi-file: a');
  parts.push('single-file deployed cron that writes a DB table read by an API is');
  parts.push('still a system. It does NOT have to be detector-found: a cross-cutting');
  parts.push('product spanning DB migrations + a route + a frontend page + a job is');
  parts.push('a system even if none of those pieces look like a "candidate" alone.');
  parts.push('');

  // Per-repo context goes FIRST after the framing — primes the LLM with the
  // consumer's domain vocabulary, ignore list, system-boundary opinions, and
  // any other knowledge the canonical tool can't know about. Renders only
  // when `docs/systems/_context.md` exists in the repo.
  if (inputs.repoContext) {
    parts.push('## Repo-specific context (hand-authored — TRUST THIS over inferences)');
    parts.push('The maintainers of this repo wrote the following to guide system');
    parts.push('synthesis. Treat it as a higher-priority signal than anything below.');
    parts.push('Use the vocabulary it defines; respect the boundaries it draws; honour');
    parts.push('any "do NOT promote X" / "always group Y" instructions it gives.');
    parts.push('');
    parts.push(inputs.repoContext);
    parts.push('');
  }

  parts.push('## Heuristic candidates (Pass 0 output)');
  parts.push('These are dir-rooted candidates the heuristic detector found.');
  parts.push('They may be over-grouped, under-grouped, or miss cross-dir systems.');
  parts.push('You may add, merge, split, or drop any of them. There is no cap on count.');
  parts.push('Pass 0 only sees JS/TS/Py/Rust source structure — it is blind to');
  parts.push('deploy configs, DB tables, and pure-business-logic dirs (no loop, no');
  parts.push('hook, no subprocess). Treat the candidate list as a starting point,');
  parts.push('not the universe.');
  parts.push('');
  for (const c of inputs.candidates) {
    parts.push(`- ${c.name} (score ${c.score}): dir=${c.dir}, signals=[${c.signals.join(', ')}], anchors=[${c.anchors.slice(0, 3).join(', ')}]`);
  }
  parts.push('');

  // Reality signal #1: what's actually deployed.
  if (inputs.deployedServices && inputs.deployedServices.length > 0) {
    parts.push('## Deployed services (parsed from deployment manifests in the repo)');
    parts.push('Every entry here corresponds to a service that exists in production.');
    parts.push('Every one of them MUST belong to some system in your output — either');
    parts.push('a dedicated system, or as a named runtime in a cross-cutting system.');
    parts.push('If you can\'t place one, flag it under `## Unplaced` at the end.');
    parts.push('');
    for (const s of inputs.deployedServices) {
      const sched = s.schedule ? ` schedule="${s.schedule}"` : '';
      const root = s.rootDir ? ` rootDir=${s.rootDir}` : '';
      const plat = s.platform ? ` (${s.platform})` : '';
      parts.push(`- ${s.name}${plat} type=${s.type}${sched}${root}  [${s.file}]`);
    }
    parts.push('');
  }

  // Reality signal #2: every top-level app/tool/package, candidate or not.
  if (inputs.topLevelApps && inputs.topLevelApps.length > 0) {
    parts.push('## Top-level inventory (apps/, tools/, packages/ — candidate or not)');
    parts.push('Every dir here exists in the repo. Some are score-0 single-file');
    parts.push('services — the detector did not surface them, but they ARE real');
    parts.push('systems and need coverage. (Pattern: a one-file index.ts or main.py');
    parts.push('that is the entrypoint for a deployed cron / worker.)');
    parts.push('');
    for (const a of inputs.topLevelApps) {
      parts.push(`- \`${a.dir}/\` — ${a.desc}`);
    }
    parts.push('');
  }

  // Reality signal #3: DB tables — the data backbone of cross-cutting systems.
  if (inputs.dbTables && inputs.dbTables.length > 0) {
    parts.push('## DB tables (from SQL migrations — the persistent state graph)');
    parts.push('Tables tell you about cross-cutting systems the detector misses:');
    parts.push('a table written by a cron + read by an API + rendered by a frontend');
    parts.push('page is ONE system, no matter how scattered its files are. Every');
    parts.push('table here should be the output of some system in your map.');
    parts.push('');
    parts.push(inputs.dbTables.join(', '));
    parts.push('');
  }

  // Reality signal #4: HTTP surface — routes/handlers that have no candidate dir.
  if (inputs.httpSurface && inputs.httpSurface.length > 0) {
    parts.push('## HTTP routes / handlers (basenames discovered in routes/handlers dirs)');
    parts.push('Each is an HTTP surface. Routes don\'t score on the detector (no');
    parts.push('loop, no hook), but a route + its service layer + its frontend');
    parts.push('consumer + its DB writes is a real system. The user-facing product');
    parts.push('features of this repo will mostly hide here.');
    parts.push('');
    parts.push(inputs.httpSurface.join(', '));
    parts.push('');
  }

  parts.push('## docgen-generated dir summaries (auto-updated per push)');
  parts.push('Includes BOTH candidate dirs and top-level apps. The non-candidate');
  parts.push('summaries are how you discover single-file / business-logic-only');
  parts.push('systems the detector missed.');
  parts.push('');
  for (const s of inputs.docgenSummaries) {
    parts.push(`### ${s.dir}`);
    parts.push(s.summary.slice(0, 1500));
    parts.push('');
  }

  parts.push('## Coordinator file snippets (current code, source of truth)');
  for (const s of inputs.coordinatorSnippets) {
    parts.push('```');
    parts.push(s.snippet);
    parts.push('```');
    parts.push('');
  }

  parts.push('## Import graph between candidate dirs');
  if (inputs.importGraph.length === 0) parts.push('(no cross-candidate imports detected)');
  for (const e of inputs.importGraph) {
    parts.push(`${e.from} -> ${e.to} (${e.weight} refs)`);
  }
  parts.push('');

  parts.push('## Recent commits per candidate (last 10 each)');
  for (const g of inputs.gitLogs) {
    parts.push(`### ${g.dir}`);
    parts.push(g.log.slice(0, 1000));
    parts.push('');
  }

  if (inputs.priorHypothesis) {
    parts.push('## Prior _hypothesis.md (previous run — KEEP IT STICKY)');
    parts.push('A prior carving of this repo into systems already exists below.');
    parts.push('Treat its system NAMES and BOUNDARIES as the default. Keep them.');
    parts.push('Only split a prior system into two, merge two into one, rename,');
    parts.push('add, or remove a system when the CODE materially changed in a way');
    parts.push('that demands it — and when you do, say WHY in the `## Notes` section.');
    parts.push('Stable naming run-to-run matters MORE than a marginally better');
    parts.push('carving: downstream per-system manifests, categories, and links all');
    parts.push('key off these names, and re-carving breaks them. Do not churn for');
    parts.push('its own sake. In particular: do NOT split a prior system that scored');
    parts.push('fine into thinner pieces (e.g. carving a "viewer" or an "evals"');
    parts.push('sub-system out of a larger pipeline that already covered them) — that');
    parts.push('manufactures junk thin systems and is exactly the failure to avoid.');
    parts.push('');
    parts.push(inputs.priorHypothesis.slice(0, 4000));
    parts.push('');
  }

  if (inputs.priorSystems.length > 0) {
    parts.push('## Existing docs/systems/*.md manifests (previously validated)');
    parts.push('Treat as "what we previously concluded — still true?"');
    parts.push('Keep what matches code. Update what changed. Flag invalidated.');
    parts.push('');
    for (const s of inputs.priorSystems) {
      parts.push(`### ${s.name}`);
      parts.push(s.summary.slice(0, 800));
      parts.push('');
    }
  }

  parts.push('## Your task');
  parts.push('Identify the real systems in this repository. Emit YAML.');
  parts.push('');
  parts.push('### Per-system fields');
  parts.push('- `name`        kebab-case identifier');
  parts.push('- `kind`        one of: pipeline | hook | installer | gate | loop-driver | data-product');
  parts.push('                  - pipeline: multi-stage transform with explicit input→output flow');
  parts.push('                  - hook: fires on a Claude / git / CI event (PreToolUse, PostToolUse, push, ...)');
  parts.push('                  - installer: one-shot setup that wires hooks / scaffolds dirs / vendors code');
  parts.push('                  - gate: pass/fail check that blocks downstream propagation (CI test, validator)');
  parts.push('                  - loop-driver: long-running coordinator with a tick / cycle');
  parts.push('                  - data-product: owns + serves a queryable artifact (DB table, dashboard, API)');
  parts.push('                Used by the overview to group systems into subgraphs and decide whether');
  parts.push('                the body needs a Closing Arrow section. Installers and gates do NOT loop.');
  parts.push('- `summary`     1-2 sentences. Name the verb (what it does), the');
  parts.push('                trigger (cron / webhook / user), the output');
  parts.push('                (DB table / chain tx / TG message / dashboard pixel).');
  parts.push('- `globs`       file patterns covering ALL pieces — including the');
  parts.push('                deployed entrypoint, the API routes it hits, the DB');
  parts.push('                migration that owns its tables, AND the frontend');
  parts.push('                consumer if any. A system that owns a DB table but');
  parts.push('                whose globs don\'t include the migration is wrong.');
  parts.push('- `closes_loop_via`  where output flows back into something useful. Use one of');
  parts.push('                     these short tokens as the FIRST word, so the overview can');
  parts.push('                     auto-route this system\'s feedback arrow back to a synthetic');
  parts.push('                     anchor node (Claude / host-repo / etc.):');
  parts.push('                       `next_llm_turn` — output is re-injected into Claude');
  parts.push('                       `host_repo`     — output edits files in the host repo');
  parts.push('                       `db_table`      — output writes to a DB table');
  parts.push('                       `chain_tx`      — output is an on-chain transaction');
  parts.push('                       `tg_message`    — output is a Telegram message');
  parts.push('                       `dashboard`     — output is read by a dashboard');
  parts.push('                       `none`          — one-shot, does not loop (installer / gate)');
  parts.push('                     Free-text after the token is fine: `next_llm_turn — via PreToolUse hook`.');
  parts.push('- `consumes`    other system names whose output this one reads');
  parts.push('- `runtimes`    optional list of deployed service names (the values');
  parts.push('                under "Deployed services" above) that run this system.');
  parts.push('                Helps an operator grep for the right page when a');
  parts.push('                service misbehaves in production.');
  parts.push('');
  parts.push('### Quality bar');
  parts.push('- **Single-file deployed services count.** If a one-file');
  parts.push('  `<app>/index.ts` (or `__main__.py`, etc.) is listed in a');
  parts.push('  deployment manifest as a cron/worker/web service, it gets a');
  parts.push('  system page. Don\'t skip it just because the detector scored it 0.');
  parts.push('- **Cross-cutting products count as ONE system, not N.** A product');
  parts.push('  whose pieces are scattered across DB migration + an HTTP route +');
  parts.push('  a scheduled job + a frontend page is a single system. Its globs');
  parts.push('  must include all four pieces. Look at the DB-tables list above —');
  parts.push('  if a table is written by a job and read by a route, that pair is');
  parts.push('  the spine of a cross-cutting system.');
  parts.push('- **Routes without a candidate dir count.** Pure business-logic');
  parts.push('  routes (HTTP handler + service layer + frontend consumer, no loop');
  parts.push('  / hook / subprocess) are invisible to the detector but are often');
  parts.push('  the user-facing products of the repo. Promote them.');
  parts.push('- **Families of similar instructions / handlers count as one');
  parts.push('  grouped system.** When several files share a SHAPE (a set of');
  parts.push('  `refund_*` instructions, a set of `withdraw_*` admin flows, a set');
  parts.push('  of `*Routes` that all do CRUD on one domain), group them — don\'t');
  parts.push('  bury them as footnotes in an adjacent system.');
  parts.push('- **Skip pure build / test / lint / CI tooling** unless it itself');
  parts.push('  owns a feedback loop (a doc generator, an evaluator, a release');
  parts.push('  bot, a hook installer).');
  parts.push('- **Prefer the prior carving when one exists.** If a prior');
  parts.push('  `_hypothesis.md` is shown above, keep its system names and');
  parts.push('  boundaries by default — only re-carve when the code materially');
  parts.push('  changed, and justify any split / merge / rename / add / remove in');
  parts.push('  `## Notes`. Splitting a previously-fine system into thinner pieces');
  parts.push('  is the failure to avoid; stable names beat marginally-better ones.');
  parts.push('');
  parts.push('### Coverage check — DO THIS LAST');
  parts.push('Before emitting your YAML, mentally walk three lists and verify');
  parts.push('every entry maps to some system in your output:');
  parts.push('  1. Every entry in "Deployed services" above');
  parts.push('  2. Every dir in "Top-level inventory" above');
  parts.push('  3. Every table in "DB tables" above');
  parts.push('If an item doesn\'t appear in any system\'s globs or runtimes, you\'ve');
  parts.push('missed a system. Add it, or fold it explicitly into an existing one');
  parts.push('whose globs you broaden to include it.');
  parts.push('');
  parts.push('Output format: a single YAML document starting with `systems:`. After');
  parts.push('the YAML, you may append a `## Notes` section calling out any');
  parts.push('decisions a human reviewer should sanity-check (merges, splits,');
  parts.push('items you deliberately did not promote to systems).');

  return parts.join('\n');
}

/**
 * Call the LLM. Runner is injectable for tests (default: spawn `claude -p`).
 */
async function callLLM(prompt, { runner, model = 'claude-opus-4-7', timeoutMs = 12 * 60_000 } = {}) {
  if (runner) return runner(prompt);
  // Pass 1 is a single call = single point of failure. Retry transient
  // claude -p blips (exit 1 / timeout) so one flake doesn't abort the sweep.
  return withRetry(() => new Promise((resolve, reject) => {
    const args = ['-p', '--model', model, '--output-format', 'text'];
    const child = spawn('claude', args);
    const chunks = [];
    const errs = [];
    let timer = setTimeout(() => {
      child.kill('SIGKILL');
      reject(new Error(`claude -p timed out after ${timeoutMs}ms`));
    }, timeoutMs);
    child.stdout.on('data', c => chunks.push(c));
    child.stderr.on('data', c => errs.push(c));
    child.on('close', code => {
      clearTimeout(timer);
      if (code === 0) resolve(Buffer.concat(chunks).toString('utf8'));
      else reject(new Error(`claude -p exited ${code}: ${Buffer.concat(errs).toString('utf8').slice(0, 500)}`));
    });
    child.on('error', e => { clearTimeout(timer); reject(e); });
    child.stdin.end(prompt);
  }));
}

/**
 * Wrap the LLM response into a _hypothesis.md file with front-matter
 * metadata. Returns the file content.
 */
export function buildHypothesisMd(llmResponse, { generatedAt = new Date().toISOString(), model = 'claude-opus-4-7' } = {}) {
  return `<!-- auto-generated by systems-registry Pass 1 — do not hand-edit. -->
<!-- Run \`tools/systems-registry/cli.mjs hypothesis\` to refresh. -->
---
generated_at: ${generatedAt}
generator: ${model}
schema_version: 1
---

# Systems hypothesis

${llmResponse.trim()}
`;
}

/**
 * Full Pass 1 entry point. Gathers inputs, builds prompt, calls LLM,
 * writes _hypothesis.md. Returns { outPath, prompt, response }.
 */
export async function runPass1(repoRoot, { runner, dryRun = false, model } = {}) {
  const inputs = gatherInputs(repoRoot);
  const prompt = buildPrompt(inputs);
  if (dryRun) {
    return { prompt, response: null, outPath: null, inputs };
  }
  const response = await callLLM(prompt, { runner, model });
  const md = buildHypothesisMd(response, { model });
  const outPath = join(repoRoot, PRIOR_HYPOTHESIS_PATH);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, md);
  return { outPath, prompt, response, inputs };
}
