import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  extractDocgenSummary,
  gatherInputs,
  buildPrompt,
  buildHypothesisMd,
  runPass1,
} from './pass1.mjs';

function makeFixture() {
  const root = mkdtempSync(join(tmpdir(), 'sr-pass1-'));

  // Candidate 1: tools/foo with 3 coordinated files
  mkdirSync(join(root, 'tools/foo'), { recursive: true });
  writeFileSync(join(root, 'tools/foo/run.mjs'),
    "import { capture } from './capture.mjs';\nimport { score } from './score.mjs';\n" +
    "import { writeFileSync } from 'node:fs';\nimport { spawn } from 'node:child_process';\n" +
    "while (true) { writeFileSync('s.json', '1'); spawn('echo', ['x']); }\n");
  writeFileSync(join(root, 'tools/foo/capture.mjs'), 'export const capture = () => {};\n');
  writeFileSync(join(root, 'tools/foo/score.mjs'), 'export const score = () => {};\n');
  writeFileSync(join(root, 'tools/foo/run.test.mjs'), "import { test } from 'node:test';\ntest('a', () => {});");
  writeFileSync(join(root, 'tools/foo/capture.test.mjs'), "import { test } from 'node:test';\ntest('b', () => {});");
  writeFileSync(join(root, 'tools/foo/score.test.mjs'), "import { test } from 'node:test';\ntest('c', () => {});");
  writeFileSync(join(root, 'tools/foo/README.md'),
    '<!-- auto-generated by docgen -->\n\n## Purpose\nFoo does the thing.\n\n## Map\n- run.mjs: orchestrator\n\n## Other\nignored\n');

  return root;
}

describe('extractDocgenSummary', () => {
  it('pulls only Purpose and Map sections from a docgen-marked README', () => {
    const text = '<!-- auto-generated by docgen -->\n\n## Purpose\nthe purpose\n\n## Map\nthe map\n\n## Other\nignored';
    const summary = extractDocgenSummary(text);
    assert.match(summary, /Purpose/);
    assert.match(summary, /the purpose/);
    assert.match(summary, /Map/);
    assert.match(summary, /the map/);
    assert.doesNotMatch(summary, /ignored/);
  });

  it('returns empty string for hand-written README (no docgen marker)', () => {
    const text = '# Hand-written\n\n## Purpose\nignored\n';
    assert.equal(extractDocgenSummary(text), '');
  });

  it('returns empty string for null/undefined', () => {
    assert.equal(extractDocgenSummary(''), '');
    assert.equal(extractDocgenSummary(null), '');
  });
});

describe('gatherInputs', () => {
  it('collects candidates + docgen summaries + coordinator snippets', () => {
    const root = makeFixture();
    try {
      const inputs = gatherInputs(root);
      assert.ok(inputs.candidates.length >= 1);
      assert.ok(inputs.docgenSummaries.length >= 1);
      assert.match(inputs.docgenSummaries[0].summary, /Foo does the thing/);
      assert.ok(inputs.coordinatorSnippets.length >= 1);
      assert.match(inputs.coordinatorSnippets[0].snippet, /run\.mjs/);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('skips hand-written READMEs (no docgen marker)', () => {
    const root = makeFixture();
    writeFileSync(join(root, 'tools/foo/README.md'), '# hand-written\n\nlies here\n');
    try {
      const inputs = gatherInputs(root);
      assert.equal(inputs.docgenSummaries.length, 0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('returns priorHypothesis: null when no prior run', () => {
    const root = makeFixture();
    try {
      const inputs = gatherInputs(root);
      assert.equal(inputs.priorHypothesis, null);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('reads prior _hypothesis.md when it exists', () => {
    const root = makeFixture();
    mkdirSync(join(root, 'docs/systems'), { recursive: true });
    writeFileSync(join(root, 'docs/systems/_hypothesis.md'), '# prior hypothesis\nstuff\n');
    try {
      const inputs = gatherInputs(root);
      assert.match(inputs.priorHypothesis || '', /prior hypothesis/);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('reads prior docs/systems/*.md manifests', () => {
    const root = makeFixture();
    mkdirSync(join(root, 'docs/systems'), { recursive: true });
    writeFileSync(join(root, 'docs/systems/widget.md'),
      '---\nname: widget\nsummary: the widget\nstatus: active\n---\n\n# widget\n\nbody here');
    try {
      const inputs = gatherInputs(root);
      assert.equal(inputs.priorSystems.length, 1);
      assert.equal(inputs.priorSystems[0].name, 'widget');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe('buildPrompt', () => {
  it('assembles all expected sections', () => {
    const inputs = {
      candidates: [{ name: 'foo', dir: 'tools/foo', score: 5, signals: ['coordinator', 'loop'], anchors: ['tools/foo/**'] }],
      docgenSummaries: [{ dir: 'tools/foo', summary: '## Purpose\nfoo' }],
      coordinatorSnippets: [{ dir: 'tools/foo', snippet: 'console.log("hi");' }],
      importGraph: [{ from: 'foo', to: 'bar', weight: 3 }],
      gitLogs: [{ dir: 'tools/foo', log: 'abc123 commit msg' }],
      priorHypothesis: null,
      priorSystems: [],
    };
    const prompt = buildPrompt(inputs);
    assert.match(prompt, /Heuristic candidates/);
    assert.match(prompt, /docgen-generated dir summaries/);
    assert.match(prompt, /Coordinator file snippets/);
    assert.match(prompt, /Import graph/);
    assert.match(prompt, /Recent commits/);
    assert.match(prompt, /Your task/);
    assert.match(prompt, /foo/);
  });

  it('includes prior hypothesis section when present', () => {
    const inputs = {
      candidates: [], docgenSummaries: [], coordinatorSnippets: [], importGraph: [], gitLogs: [],
      priorHypothesis: '# prior thing',
      priorSystems: [],
    };
    const prompt = buildPrompt(inputs);
    assert.match(prompt, /Prior _hypothesis/);
    assert.match(prompt, /prior thing/);
  });

  it('omits prior-hypothesis section when absent', () => {
    const inputs = {
      candidates: [], docgenSummaries: [], coordinatorSnippets: [], importGraph: [], gitLogs: [],
      priorHypothesis: null,
      priorSystems: [],
    };
    const prompt = buildPrompt(inputs);
    assert.doesNotMatch(prompt, /Prior _hypothesis/);
  });

  it('includes prior systems section when manifests exist', () => {
    const inputs = {
      candidates: [], docgenSummaries: [], coordinatorSnippets: [], importGraph: [], gitLogs: [],
      priorHypothesis: null,
      priorSystems: [{ name: 'widget', summary: 'the widget body' }],
    };
    const prompt = buildPrompt(inputs);
    assert.match(prompt, /Existing docs\/systems/);
    assert.match(prompt, /widget/);
  });
});

describe('buildHypothesisMd', () => {
  it('wraps LLM response with marker + front-matter', () => {
    const md = buildHypothesisMd('systems:\n  - name: foo\n    summary: stuff');
    assert.match(md, /auto-generated by systems-registry Pass 1/);
    assert.match(md, /generated_at:/);
    assert.match(md, /generator:/);
    assert.match(md, /schema_version: 1/);
    assert.match(md, /name: foo/);
  });
});

describe('runPass1 with injected runner', () => {
  it('full round-trip: gather inputs, build prompt, call (mocked) LLM, write _hypothesis.md', async () => {
    const root = makeFixture();
    try {
      const mockResponse = 'systems:\n  - name: foo\n    summary: a test system\n    globs:\n      - tools/foo/**\n';
      let capturedPrompt = null;
      const runner = async (prompt) => { capturedPrompt = prompt; return mockResponse; };
      const result = await runPass1(root, { runner });
      assert.ok(result.outPath);
      assert.match(capturedPrompt, /Heuristic candidates/);
      assert.match(result.response, /name: foo/);
      assert.ok(existsSync(result.outPath));
      const written = readFileSync(result.outPath, 'utf8');
      assert.match(written, /a test system/);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('--dry-run returns prompt without calling LLM and without writing', async () => {
    const root = makeFixture();
    try {
      const runner = async () => { throw new Error('should NOT be called in dry-run'); };
      const result = await runPass1(root, { runner, dryRun: true });
      assert.ok(result.prompt);
      assert.equal(result.response, null);
      assert.equal(result.outPath, null);
      assert.ok(!existsSync(join(root, 'docs/systems/_hypothesis.md')));
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
