import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { runPipeline, readRunReport } from './run-pipeline.mjs';

function makeFixture() {
  const root = mkdtempSync(join(tmpdir(), 'sr-pipeline-'));
  mkdirSync(join(root, 'apps/foo'), { recursive: true });
  writeFileSync(join(root, 'apps/foo/run.mjs'),
    "import { capture } from './capture.mjs';\nimport { score } from './score.mjs';\n" +
    "import { writeFileSync } from 'node:fs';\nimport { spawn } from 'node:child_process';\n" +
    "while (true) { writeFileSync('s.json', '1'); spawn('echo', ['x']); }\n");
  writeFileSync(join(root, 'apps/foo/capture.mjs'), 'export const capture = () => {};\n');
  writeFileSync(join(root, 'apps/foo/score.mjs'), 'export const score = () => {};\n');
  writeFileSync(join(root, 'apps/foo/run.test.mjs'), "import { test } from 'node:test';\ntest('a', () => {});");
  writeFileSync(join(root, 'apps/foo/capture.test.mjs'), "import { test } from 'node:test';\ntest('b', () => {});");
  writeFileSync(join(root, 'apps/foo/score.test.mjs'), "import { test } from 'node:test';\ntest('c', () => {});");
  writeFileSync(join(root, 'apps/foo/README.md'),
    '<!-- auto-generated by docgen -->\n\n## Purpose\nFoo does the thing.\n\n## Map\n- run.mjs: orchestrator\n');
  return root;
}

// A mock LLM runner that detects whether it's a Pass 1 or Pass 2 prompt
// and emits a deterministic, valid response for each.
function makeMockRunner({ qualityScore = null } = {}) {
  // qualityScore: if set, the validator branch returns those dimension
  // scores; default null → a clean 9 (no issues) so refine passes round 1.
  return async (prompt) => {
    if (prompt.includes('Scoring rubric') || prompt.includes('DO NOT TRUST THE DOCUMENT')) {
      const n = qualityScore == null ? 9 : qualityScore;
      const clean = qualityScore == null || qualityScore >= 8.5;
      return JSON.stringify({
        scores: { correctness: n, completeness: n, sizing: n, diagram: n, clarity: n, overall: n },
        verdict: clean ? 'ship' : 'revise',
        issues: clean ? [] : ['a fabricated edge'],
        suggestions: [], missing: [], sizing_note: 'right-sized',
      });
    }
    if (prompt.includes('Heuristic candidates')) {
      // Pass 1: emit hypothesis YAML
      return `systems:
  - name: apps-foo
    summary: A tick-loop runner
    globs:
      - apps/foo/**
    closes_loop_via: state.json + spawn
`;
    }
    if (prompt.includes('writing a complete system manifest')) {
      // Pass 2: emit a complete body
      return `---
name: apps-foo
summary: A tick-loop runner that snapshots, scores, and spawns each tick
globs:
  - apps/foo/**
status: active
---

# apps-foo

## What it does

The runFoo coordinator imports capture and score and runs them in a tick loop.

## The loop

\`\`\`mermaid
flowchart LR
  a[start] --> b[capture] --> c[score] --> d[persist] --> a
\`\`\`

## Anchors

- \`apps/foo/run.mjs\` — coordinator
- \`apps/foo/capture.mjs\` — snapshot
- \`apps/foo/score.mjs\` — reducer

## Closing arrow

Writes state.json each tick; spawns subprocess.

## Invariants

- Loop runs forever
- State is overwritten each tick

## Failure modes

- Disk full crashes the loop
- spawn() failure crashes the loop

## Where to start reading

1. apps/foo/run.mjs
2. apps/foo/capture.mjs
3. apps/foo/score.mjs
`;
    }
    return '(unknown prompt type)';
  };
}

describe('runPipeline (end-to-end with mocked LLM)', () => {
  it('runs Pass 0 → 1 → 2 → 2.5 → ships an active manifest', async () => {
    const root = makeFixture();
    try {
      const out = [];
      const runner = makeMockRunner();
      const result = await runPipeline(root, {
        write: (s) => out.push(s),
        runner,
        llmVet: false,  // no LLM in vet for hermetic test
      });
      assert.equal(result.results.length, 1);
      assert.equal(result.results[0].name, 'apps-foo');
      assert.equal(result.results[0].status, 'active');
      assert.ok(existsSync(join(root, 'docs/systems/_hypothesis.md')));
      assert.ok(existsSync(join(root, 'docs/systems/apps-foo.md')));
      // Body should be the mock body (not an error)
      const body = readFileSync(join(root, 'docs/systems/apps-foo.md'), 'utf8');
      assert.match(body, /A tick-loop runner/);
      assert.match(body, /flowchart LR/);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('ships active when the only vet issue is an unfixable runtime-artifact glob', async () => {
    const root = makeFixture();
    // Add a glob in the mock Pass 2 body that references a runtime dir
    // that doesn't exist — this is an "unfixable" issue (glob-no-matches).
    try {
      const runner = async (prompt) => {
        if (prompt.includes('Heuristic candidates')) {
          return 'systems:\n  - name: apps-foo\n    summary: x\n    globs:\n      - apps/foo/**\n';
        }
        // Pass 2 body references a runtime glob that won't match
        return `---
name: apps-foo
summary: tick loop
globs:
  - apps/foo/**
  - lab/data/runtime/**
status: active
---

# apps-foo

## What it does
The runFoo coordinator loops.

## The loop
\`\`\`mermaid
flowchart LR
  a[x] --> b[y]
\`\`\`

## Anchors
- \`apps/foo/run.mjs\` — coordinator

## Closing arrow
state.

## Invariants
- loops

## Failure modes
- crash

## Where to start reading
1. apps/foo/run.mjs
`;
      };
      const result = await runPipeline(root, { write: () => {}, runner, llmVet: false });
      // The lab/data/runtime/** glob matches nothing → glob-no-matches issue,
      // but it's unfixable → system should still ship 'active', no revise calls.
      assert.equal(result.results[0].status, 'active');
      assert.equal(result.results[0].attempts, 0);  // revise must NOT have fired
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('persists docs/systems/.run-report.json with per-system observability', async () => {
    const root = makeFixture();
    try {
      const runner = makeMockRunner();
      await runPipeline(root, { write: () => {}, runner, llmVet: false });
      const report = readRunReport(root);
      assert.ok(report, 'run-report.json should exist');
      assert.equal(report.schemaVersion, 1);
      assert.ok(report.startedAt && report.finishedAt);
      assert.equal(report.minScore, 7);
      assert.equal(report.systems.length, 1);
      const sys = report.systems[0];
      assert.equal(sys.name, 'apps-foo');
      assert.equal(sys.status, 'active');
      assert.equal(typeof sys.qualityScore, 'number');
      assert.ok(Array.isArray(sys.finalProblems));
      assert.ok(Array.isArray(sys.initialProblems));
      assert.equal(typeof sys.reviseAttempts, 'number');
      // Summary echo
      assert.equal(report.summary.total, 1);
      assert.equal(report.summary.active, 1);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('telemetry captures Pass 1 + per-system Pass 2 timings', async () => {
    const root = makeFixture();
    try {
      const runner = makeMockRunner();
      const { telemetry } = await runPipeline(root, { write: () => {}, runner, llmVet: false });
      assert.ok(telemetry.startedAt);
      assert.ok(telemetry.finishedAt);
      assert.equal(telemetry.summary.active, 1);
      assert.equal(telemetry.summary.needsReview, 0);
      assert.ok(telemetry.steps.some(s => s.pass === 1));
      assert.ok(telemetry.steps.some(s => s.pass === 2 && s.system === 'apps-foo'));
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

describe('runPipeline quality phase (Pass 2.7)', () => {
  it('default-on: scores each system, stamps quality_score, avg in summary', async () => {
    const root = makeFixture();
    try {
      const runner = makeMockRunner();   // clean 9
      const { telemetry, results } = await runPipeline(root, { write: () => {}, runner });
      assert.equal(results[0].qualityScore, 9);
      assert.equal(telemetry.summary.avgQualityScore, 9);
      assert.equal(results[0].status, 'active');
      // quality_score stamped into the manifest front-matter
      const body = readFileSync(join(root, 'docs/systems/apps-foo.md'), 'utf8');
      assert.match(body, /quality_score:\s*9/);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('gates below --min-score to needs-review', async () => {
    const root = makeFixture();
    try {
      const runner = makeMockRunner({ qualityScore: 5 });  // below bar, with issues → capped 5
      const { results, telemetry } = await runPipeline(root, { write: () => {}, runner, minScore: 8.5, maxRounds: 1 });
      assert.ok(results[0].qualityScore <= 7);          // hard cap applied (issues present)
      assert.equal(results[0].status, 'needs-review');  // gated
      assert.ok(telemetry.summary.belowBar.length >= 1);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('--no-validate skips the judge entirely (qualityScore null)', async () => {
    const root = makeFixture();
    try {
      const runner = makeMockRunner();
      const { results, telemetry } = await runPipeline(root, { write: () => {}, runner, validate: false });
      assert.equal(results[0].qualityScore, null);
      assert.equal(telemetry.summary.avgQualityScore, null);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('--no-refine scores once without the regenerate loop', async () => {
    const root = makeFixture();
    try {
      const runner = makeMockRunner();
      const { results } = await runPipeline(root, { write: () => {}, runner, refine: false });
      assert.equal(results[0].qualityScore, 9);
      assert.equal(results[0].refineRounds, 0);   // no refine rounds when refine off
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

describe('runPipeline resilience', () => {
  it('one system failing (LLM throws) does not abort the sweep', async () => {
    const root = makeFixture();
    try {
      // Runner: Pass 1 ok, but Pass 2 generate throws (simulates claude -p
      // exit-1 after retries exhausted). The single-system fixture means the
      // whole per-system task throws → must be caught, marked error, sweep
      // still completes (build/summary run).
      let pass1Done = false;
      const runner = async (prompt) => {
        if (prompt.includes('Heuristic candidates')) {
          pass1Done = true;
          return `systems:\n  - name: apps-foo\n    summary: x\n    globs:\n      - apps/foo/**\n`;
        }
        throw new Error('claude -p exited 1: '); // pass 2 + everything else fails
      };
      const { telemetry, results } = await runPipeline(root, { write: () => {}, runner });
      assert.ok(pass1Done);
      assert.equal(results.length, 1);
      assert.equal(results[0].status, 'error');           // marked, not crashed
      assert.equal(telemetry.summary.errored, 1);
      assert.ok(telemetry.finishedAt);                    // sweep completed
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});

import { computeValidateScope, matchGlob } from './run-pipeline.mjs';

describe('matchGlob (incremental cost-saver)', () => {
  it('handles dir/** prefix + exact paths + single-segment wildcards', () => {
    assert.equal(matchGlob('apps/api/**', 'apps/api/src/x.ts'), true);
    assert.equal(matchGlob('apps/api/**', 'apps/api'), true);
    assert.equal(matchGlob('apps/api/**', 'apps/web/x.ts'), false);
    assert.equal(matchGlob('apps/api/src/routes/*.ts', 'apps/api/src/routes/x.ts'), true);
    assert.equal(matchGlob('apps/api/src/routes/*.ts', 'apps/api/src/routes/sub/x.ts'), false);
    assert.equal(matchGlob('exact.ts', 'exact.ts'), true);
  });
});

describe('computeValidateScope (incremental + downstream)', () => {
  const systems = [
    { name: 'a', globs: ['apps/a/**'], consumes: [] },
    { name: 'b', globs: ['apps/b/**'], consumes: ['a'] },        // downstream of a
    { name: 'c', globs: ['apps/c/**'], consumes: ['b'] },        // downstream of b
    { name: 'd', globs: ['apps/d/**'], consumes: [] },           // unrelated
  ];

  it('null changedFiles → ALL systems (full sweep)', () => {
    const s = computeValidateScope(systems, null);
    assert.deepEqual([...s].sort(), ['a', 'b', 'c', 'd']);
  });

  it('changed file in `a` includes a + b + c (transitive downstream), not d', () => {
    const s = computeValidateScope(systems, ['apps/a/src/x.ts']);
    assert.deepEqual([...s].sort(), ['a', 'b', 'c']);
    assert.ok(!s.has('d'));
  });

  it('change in d alone → only d', () => {
    const s = computeValidateScope(systems, ['apps/d/y.ts']);
    assert.deepEqual([...s], ['d']);
  });

  it('empty changedFiles array is treated as null (full scope)', () => {
    const s = computeValidateScope(systems, []);
    assert.equal(s.size, 4);
  });
});

describe('runPipeline cost controls', () => {
  it('changedFiles restricts the LLM judge to in-scope systems; out-of-scope skip', async () => {
    const root = makeFixture();
    try {
      // Mock runner: pass 1 emits ONE system (apps-foo). Validator branch only
      // ever runs for in-scope systems — we'll pass changedFiles for a path
      // that does NOT match apps/foo, so the judge is skipped.
      let judgeCalls = 0;
      const runner = async (prompt) => {
        if (prompt.includes('Scoring rubric') || prompt.includes('DO NOT TRUST THE DOCUMENT')) {
          judgeCalls++;
          return '{"scores":{"correctness":9,"completeness":9,"sizing":9,"diagram":9,"clarity":9},"verdict":"ship","issues":[],"missing":[],"suggestions":[],"sizing_note":""}';
        }
        if (prompt.includes('Heuristic candidates')) {
          return `systems:\n  - name: apps-foo\n    summary: x\n    globs:\n      - apps/foo/**\n`;
        }
        return `---\nname: apps-foo\nsummary: x\nglobs:\n  - apps/foo/**\nstatus: active\n---\n# apps-foo\n## What it does\nstuff\n## The loop\n\`\`\`mermaid\nflowchart LR\n  a --> b\n\`\`\`\n## Anchors\n- apps/foo/run.mjs — coordinator\n## Closing arrow\nstate.json\n## Invariants\n- one\n## Failure modes\n- one\n## Where to start reading\n1. apps/foo/run.mjs\n`;
      };
      const { results } = await runPipeline(root, {
        write: () => {}, runner,
        changedFiles: ['unrelated/path.ts'],   // doesn't match apps/foo/**
      });
      assert.equal(results.length, 1);
      assert.equal(results[0].skipReason, 'incremental-out-of-scope');
      assert.equal(judgeCalls, 0, 'no LLM judge calls when out of scope');
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it('token budget abort fires when meter exceeds budget mid-sweep', async () => {
    const root = makeFixture();
    try {
      const runner = async (prompt) => {
        // Return a large response so we burn tokens fast — each call is enough
        // to blow a tiny budget.
        if (prompt.includes('Heuristic candidates')) {
          return `systems:\n  - name: apps-foo\n    summary: x\n    globs:\n      - apps/foo/**\n` + ' '.repeat(2000);
        }
        return '---\nname: apps-foo\nsummary: x\nglobs:\n  - apps/foo/**\nstatus: active\n---\n' + ' '.repeat(5000);
      };
      const { telemetry } = await runPipeline(root, {
        write: () => {}, runner,
        validate: false,           // keep this test focused on the meter, not the judge
        maxTokensEst: 100,         // tiny budget so we trip it immediately
      });
      assert.equal(telemetry.summary.budgetAborted, true);
      // tokensEst should equal-or-exceed the (tiny) budget when abort fired.
      assert.ok(telemetry.summary.tokensEst >= telemetry.summary.tokenBudget);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});
